### ISSUE TITLE
RFE: customization of description for timeline snapshots using systemd timer files

### ISSUE THREAD

**Issue by oniko** [openSUSE/snapper#132]
Hi Arvin,

Just bouncing the RFE I got today. side note: I enabled systemd timer files (and services) in Fedora 21+, so it's not literally an upstream issue since AFAIK it's not enabled by default yet. Just for the record.

Here's the original RFE:

In Fedora 20, automated hourly snapshots were created thru the use of a /etc/cron.hourly/snapper script.

This script created snapshots with a Description of "timeline", which is plain useless especially because next field "Cleanup" also displays "timeline", which is far enough to visually identify a timeline entry. No need for seing "timeline timeline" ;-)

So I used to customize the description string to the much more useful output of "`uname -r`" just by editing said /etc/cron.hourly/snapper script.

In Fedora 21, all those cron files are gone and the automated snapshots are managed using pure systemd timers.

With the result that I cannot customize the description the way I used to do.

It looks like that the involved systemd helper files are all-binary, so I cannot edit them easily.

I believe that the used string resides in binary "/usr/lib/snapper/systemd-helper".

I'd love a fix allowing to customize the "description" string for generated snapshots, including the output of a command such as `uname -r`...

Kind regards.

**Comment by aschnell** [comment]
With the latest version on GitHub you can now pass userdata to systemd-helper (userdata seems better than description). This can be used as following:

```ExecStart=/bin/sh -c 'UNAME=`uname -r` ; /usr/lib/snapper/systemd-helper --timeline --userdata "uname=$${UNAME}"'```
