### ISSUE TITLE
[RFE] implement dnf plugin

### ISSUE THREAD

**Issue by igor-raits** [openSUSE/snapper#134]
DNF is coming to F22 as default package manager.

I think would be great to integrate snapper with dnf. I can help with writing this, but I don't know how snapper works and don't have time to investigating.

**Comment by jwatt** [comment]
> https://bugzilla.redhat.com/show_bug.cgi?id=1173542
> because no pre/post-transaction I'll provide just function to create snapshot after transaction.

For anyone else digging up this old issue and wondering like I did - DNF now has pre/post-transaction hooks and [pre/post-transaction snapshot support was added to the DNF plugin in July 2017](https://github.com/rpm-software-management/dnf-plugins-extras/commit/a6d9bc41a2ec8ef189efdc05fbd1e95dc16fa7fe).
