### ISSUE TITLE
Provide  PPA or repository for Ubuntu 14.04, 14.10 with fresh snapper versions (0.2.4 and newer)

### ISSUE THREAD

**Issue by MurzNN** [openSUSE/snapper#140]
At now there are snapper repository only for too old Ubuntu versions:
http://software.opensuse.org/download/package?project=filesystems:snapper&package=snapper
here is repository only for older versions
xUbuntu 13.02
xUbuntu 13.04

This versions is too old, and many Ubuntu users must use old version 0.1.8 of snapper from distibutive: http://packages.ubuntu.com/search?keywords=snapper&searchon=names&suite=all&section=all

Please create repository with fresh snapper versions (0.2.4 and newer) for new Ubuntu versions 14.04 LTS and 14.10

And maybe will be easier to do this via PPA using launchpad.net https://help.launchpad.net/Packaging/PPA ?

**Comment by aschnell** [comment]
Builds now for Ubuntu 13.04 - 14.10 in openSUSE buildservice (https://build.opensuse.org/project/monitor/filesystems:snapper).

**Comment by MurzNN** [comment]
Thanks, all works well!
