### ISSUE TITLE
Clarification in how contribute for translators

### ISSUE THREAD

**Issue by jristz** [openSUSE/snapper#146]
Actually there is no documentation or hint in how contribute translation and translation fixes (or fix "miswrittings") in a easy way.

A hint on how or what to do to help the project to get translated.

Maybe in the README something like "If you want contribute you can fork and send request the fixes or translations updates" (really generic text example, I know).

**Comment by aschnell** [comment]
The README in the po directory does give some advice but the link there is very old.

I must admit that I don't know how the openSUSE Localization Team coordinates its work. Does the website (https://en.opensuse.org/OpenSUSE_Localization_Guide) provide enough information for you?

**Comment by jristz** [comment]
2015-02-13 11:23 GMT-03:00 Arvin Schnell <notifications@github.com>:

> The README in the po directory does give some advice but the link there is
> very old.
>
> I must admit that I don't know how the openSUSE Localization Team
> coordinates its work. Does the website (
> https://en.opensuse.org/OpenSUSE_Localization_Guide) provide enough
> information for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openSUSE/snapper/issues/146#issuecomment-74260347>.
>


Mostly, yeah, but it outdated too, and have one or two "comming soon!",
also it a little specific to OpenSuse progs and even list yast and lcn only.

Maybe if that page is finished or conplete or less Suse specific (I mean
adding snapper and other tools info about joining) could be used intead of
the readme.
-- 
*Pablo Lezaeta*

**Comment by aschnell** [comment]
I have made a bug report for the Wiki page (https://bugzilla.suse.com/show_bug.cgi?id=918212).
