### ISSUE TITLE
How to open Snapper GUI interface for visual comparing snapshots

### ISSUE THREAD

**Issue by MurzNN** [openSUSE/snapper#151]
In frontpage of http://snapper.io/ site I see the screenshot: http://snapper.io/images/snapper_yast2_diff.png
But after installing snapper package I didn't see how to run this GUI interface of snapper. I use Ubuntu linux. Is there any command-line option of additional software needed for run snapper GUI? Can you describe this in documentation?

**Comment by rsking84** [comment]
I'm wondering this too (I just switched to Linux Mint from OpenSUSE 13.2). In the screenshot the GUI is a part of YaST, which is only available in OpenSUSE. I'm not sure that there is a separate GUI.

**Comment by aschnell** [comment]
The screenshot is indeed from YaST.

You could try https://github.com/ricardomv/snapper-gui.

**Comment by aschnell** [comment]
I have added links to the known GUIs in the FAQ.

**Comment by MurzNN** [comment]
Thanks!
