### ISSUE TITLE
Instructions for GRUB menu entry to boot read-only snapshots

### ISSUE THREAD

**Issue by rsking84** [openSUSE/snapper#153]
OpenSUSE 13.2 includes a GRUB menu entry that allows the user to select a snapshot and boot into it (read only). This is a fantastic system recovery tool. I'd like to set this up on Ubuntu / Linux Mint. 

Can you please include instructions in a blog post and/or the snapper documentation?

**Comment by aschnell** [comment]
Without extensions for grub this will not work as easy as in openSUSE 13.2. For other distributions you can follow the example in http://snapper.io/2014/04/29/rollback.html.
