### ISSUE TITLE
Option to run command before and after snapshot is taken.

### ISSUE THREAD

**Issue by penetal** [openSUSE/snapper#162]
An option to run a command before and after a snapshot is taken could be useful to some.
Hypothetical config options could be:
```
CMD_PRE="who > /active_users"
CMD_POST="rm /active_users"
```
I would mostly use this to update grub, which searches out snapshots of the root partition so I can boot from a previous environment if necessary, but it can be useful for what ever people might need, maybe like using `btrfs send` to take backups of the new snapshot.

**Comment by aschnell** [comment]
Yes, see old but still open issue https://github.com/openSUSE/snapper/issues/28.

**Comment by lukolszewski** [comment]
How to use this feature? I'd love to be able to run a script before and after a snapshot.

**Comment by aschnell** [comment]
Plugins are documented in the snapper man page.
