### ISSUE TITLE
Re-including some excluded directories in root filesystem snapshots

### ISSUE THREAD

**Issue by darlingm** [openSUSE/snapper#170]
Regarding [Directories Excluded from Snapshots](https://www.suse.com/documentation/sled-12/book_sle_admin/data/sec_snapper_setup.html#snapper_dir-excludes), explaining that root file system snapshots do not contain all directories such as /boot/grub2/i386-pc, /home, /usr/local, etc.

I think this is a great feature.  I think it will save many users frustration.

That being said, I want to make SOME of the excluded directories included.  Even if that means editing source code, rather than a config file.  What implements this exclusion?  I downloaded the snapper git repo, and these show no results: `grep mailman -r *` or `grep i386-pc" -r *`  Is it in btfrs itself?

I want to use snapper instead of VMware snapshots.  VMware snapshots work on the virtual disk, so hit everything.  I'm long accustomed to working like this.

Under subvolid=0, I have subvolumes: root (mounted to /), .snapshots (mounted to /.snapshots), and outside-snapshots (mounted to /outside-snapshots).  I only configured snapper to operate on subvolume root, so /.snapshots and /outside-snapshots is left alone.  [Credit to this guy](https://bbs.archlinux.org/viewtopic.php?id=194491)

I am on arch, in case it's something that occurs on suse only.

P.S. If this needs source editing to snapper, would you like a pull request, or is this a "feature" you wouldn't like?

**Comment by aschnell** [comment]
Excluding directories from snapshots is done by creating subvolumes in btrfs as mentioned in
the FAQ (https://www.suse.com/documentation/sled-12/book_sle_admin/data/sec_snapper_faqs.html, http://snapper.io/faq.html). So use 'btrfs subvolume list /' and 'btrfs subvolume create ...' to control exclusion.
