### ISSUE TITLE
Snapper Config - Enable Excluded Directories

### ISSUE THREAD

**Issue by darksheer** [openSUSE/snapper#174]
I'm wanting to use Snapper to snapshot the / BTRFS partition.  Per SUSE documentation directories such as /srv, /home, etc are excluded.  For a config to enable snapshot of these directories for a complete system rollback, what modifications need to be done to the default root config?  I see the:

SUBVOLUME="/"

Do I simply add the excluded directories?  

Thx,

V

**Comment by aschnell** [comment]
You have to create btrfs subvolumes for the directories you want to exclude, see https://btrfs.wiki.kernel.org/index.php/FAQ#What_is_a_subvolume.3F. Unfortunately there is no dedicated command to convert a directory to a subvolume, see http://www.spinics.net/lists/linux-btrfs/msg33258.html.
