### ISSUE TITLE
 Checking status with snapper receiving Failure (org.freedesktop.DBus.Error.NoReply)

### ISSUE THREAD

**Issue by oniko** [openSUSE/snapper#176]
Hi Arvin,

I have some bad news for Friday. The bug I reference is reproducible also with upstream snapper (0.2.6) and it's not related to lvm only. I hope I'm getting close to the solution, will let you know about details when I have some. I fear it's related to DBus interface as being implemented in snapper but again, will provide you with details when I have some.

bug: http://bugzilla.redhat.com/show_bug.cgi?id=1229353

So only (sad) heads up for you:/

Regards
O.

**Comment by aschnell** [comment]
You are hitting the DBus message size limit. So the problem has an easy and a hard fix.

Easy: Increase size limit in /etc/dbus-1/system.conf. E.g. add:
```
  <limit name="max_incoming_bytes">100000000</limit>
  <limit name="max_outgoing_bytes">100000000</limit>
  <limit name="max_message_size">100000000</limit>
```

Hard: Implement other technique to pass the file list from server to client.

Maybe this gets better with kdbus.

**Comment by oniko** [comment]
Thank you for quick reply! Yes, increasing the limit helped workaround the issue, but I'm affraid it's only temporary solution. According to DBus docs, it seems there's a hard limit on message size which is 128 MB. This ~40MB filelist is pretty much too close to that limit. I'm affraid I can avoid the hard fix only for a limited time...

This is immediate idea (and probably wrong): what about introducing interface for splitting large messages among smaller ones:

request: GetFiles
response: "part 1, 8 more will follow"
response: "part 2"
response: "part 3"
...

But yes. This would add much more complexity given I'd have to deal with new error paths...

**Comment by oniko** [comment]
Well. the other way (and probably a lot faster) would be to pass the file-list through socket/pipe negotiated via message bus. Unfortunately we would have to parse the file-list on client-side...

**Comment by aschnell** [comment]
Yes, you have outlined the two basic ideas for a proper fix I see. One interesting modification to the first idea could be to allow clients to query a tree of files instead of a simply list. E.g.
```
GetFilesTree("/")
```
would return
```
[
  { "/etc", status, has_subtree },
  { "/usr", status, has_subtree }
]
```

The client can then continue with GetFilesTree("/etc") and GetFilesTree("/usr").

That could overall reduce the amount of transmitted data since paths are transmitted only once but at the same time increase the number of request.

A client representing the files as a tree to the user anyway could even delay the requests until the user opens a directory.

**Comment by oniko** [comment]
Hmm. I see both approaches have their own advantages. The first one would be a more work to implement...Let me see If I can figure out a fix where the second (socket pair/pipe) solution would be a sub solution of the first one... with eventual replacement with kdbus transport later

**Comment by p2004a** [comment]
Hi,

I debugged why snapperd is crashing. Here is a description:

> `DBus::Connection` constructor calls `dbus_bus_get` which calls `internal_bus_get` which sets `connection->exit_on_disconnect` to true using `dbus_connection_set_exit_on_disconnect`.
> 
> When message send out by snapperd is too big, dbus deamon closes connection. It is discovered while reading from or writing to socket, it depends on execution. Then `org.freedesktop.DBus.Local.Disconnected` signal is pushed to snapperd libdbus connection incomming messages queue. This is for example documented in `dbus_shutdown` function documentation:
> 
> ````
>  * If a shared connection is open, calling dbus_shutdown() will
>  * drain its queue of messages and disconnect it. In particular,
>  * this will result in processing of the special Disconnected
>  * signal, which may result in a call to _exit(), unless you
>  * have used dbus_connection_set_exit_on_disconnect() to disable
>  * that behaviour.
> ````
> 
> `dbus_connection_pop_message` called by `DBus::Connection::pop_message` from snapperd main loop figures out current state of connection. When it is disconnected the call stack reaches `notify_disconnected_unlocked` which removes all outgoing messages that weren't send out yet. Later `_dbus_connection_update_dispatch_status_and_unlock` is called from `dbus_connection_pop_message` which reads the `exit_on_disconnect` flag and when it is true it terminates process using `_dbus_exit` call before Disconnect signal reaches application code.

I include it for future reference.

I will try to implement catching Disconnect signal so snapperd will be able crash more gracefully printing meaningful message.

Another thing is solution to returning this big list of files. I see that #183 is still in works and it looks quite complex. What about different method: GetFilesPart(config-name, number1, number2, offset, limit) where limit and offset work like SQL LIMIT and OFFSET? It should be good enough, implementation should be quite easy and adding support to this command from in other snapperd clients like snapper-gui should be strightforward too.

I will try to implement it, and if you like idea I will send pull request.

**Comment by p2004a** [comment]
Here is the implementation of GetFilesPart: https://github.com/openSUSE/snapper/compare/master...p2004a:new-getfilespart-method

**Comment by zoopla-jb** [comment]
💀 Had this on openSUSE 15.3 today. Added the solution:

 /etc/dbus-1/system-local.conf
```
  <limit name="max_incoming_bytes">100000000</limit>
  <limit name="max_outgoing_bytes">100000000</limit>
  <limit name="max_message_size">100000000</limit>
```

**Comment by aschnell** [comment]
PR #698 implements transferring the filelist by pipe. It is partly based on PR #183 but e.g. avoids the use of Boost Serialization.
A release will some soon when the new version passes QA.

The idea with transferring a tree using many DBus calls is too slow.
