### ISSUE TITLE
improperly usurps control of the default subvolume for rollbacks

### ISSUE THREAD

**Issue by cmurf** [openSUSE/snapper#178]
It's understandable snapper changes the default subvolume to do rollbacks, because it's easy, and the alternatives require a lot more planning and cooperation. But this is really the wrong way to do this for the following reasons:

1. 'btrfs subvolume set-default' is user domain, meaning this is intended by design for to make the user's life easier, not the developer of a utility. It's a short cut for the user to mount a particular subvolume as a short cut in order to avoid having to use -o subvol= or subvolid=. It's inappropriate to take this away from the user, especially in a case where snapper is installed and used in a system by default like with openSUSE. It completely upends the consistent use of default subvolume in a non-discoverable way. There are now some Btrfs volumes where a utility owns the default subvolume, and other volumes where the user owns it, so now it's mixed. And it burdens the user with needing to know the difference in order to prevent accidentally breaking the boot of their system.

2. It makes boot more difficult to understand and troubleshoot, because there is no indication in dmesg or journalctl what subvolume is actually being booted. So if there are boot problems, now the user is burdened with having to a.) be aware of the true nature of snapshots on Btrfs as separate fs trees/subvolumes; b. have to become aware of the fact snapper does rollbacks by changing the default subvolume; c.) have to become aware of commands to determine what the actual default subvolume is, which is totally non-discoverable because they first must get the ID with one command and then use a second command to actually translate the ID into a path.

3. It drags GRUB into this, by requiring it to follow the default subvolume in order to find the new /boot. And this is incompatible with GRUB upstream, so now distros must carry their own patches to make GRUB behave differently than upstream and that's just short of a forking mess:
http://lists.gnu.org/archive/html/grub-devel/2013-10/msg00038.html

So really what needs to happen is snapper needs to learn some new tricks. It either needs to know how to modify grub.cfg; or mount the new root in a chroot and run grub2-mkconfig to make a new grub.cfg; or create Freedesktop bootloaderspec compliant boot snippets to inform the bootloader how to boot next. In my opinion, the most bootloader and distro agnostic way to do this is with bootloaderspec but that's a separate conversation.

What snapper needs to do is modify the next boot entry's kernel command line to include the rootflags boot parameter, to include the mount options for the Btrfs subvolume you want to rollback to. Now this is explicit, it's discoverable (in both dmesg and journal and messages), and thus less fragile.

I suggest snapper devs take a look at ostree, specifically Project Atomic/rpm-ostree, https://github.com/projectatomic/rpm-ostree which is able to do atomic updates and rollbacks, and does this by modifying the bootloader configuration. So maybe there's a way for snapper to do the snapshot management, and then defer the bootloader configuration changes to the part of ostree that's already written to do this.

**Comment by aschnell** [comment]
Well, snapper was enhanced to support the way SUSE does rollbacks, not the other way around.

If some distribution wants a different mechanism snapper can also support that but I will need patches.

**Comment by cmurf** [comment]
https://features.opensuse.org/319292
