### ISSUE TITLE
Provide systemd timer files

### ISSUE THREAD

**Issue by GreatEmerald** [openSUSE/snapper#18]
Seeing that snapper includes cron files for cleanup tasks, and that systemd is currently used in most distributions, I think it would be a nice idea to include systemd timer files, instead of the cron scripts, if the user has systemd installed.
Oh, and I noticed that the cron scripts also have hardcoded paths, but I don't suppose autotools can dynamically change such script files, right?

**Comment by NicoHood** [comment]
Boot snapshots would also be nice:
https://github.com/openSUSE/snapper/issues/264
