### ISSUE TITLE
Wrong German translation (typo)

### ISSUE THREAD

**Issue by davidhaller** [openSUSE/snapper#185]
https://github.com/openSUSE/snapper/blob/master/po/de.po#L564
Should be "Keine Berechtigungen." instead of "Keine Berechnungen."

I'm posting this here, because it is unclear for me how to easily submit such translations, the README wasn't very helpful.

**Comment by aschnell** [comment]
Thanks, I have informed the openSUSE translation team about the mistake.

**Comment by aschnell** [comment]
Meanwhile fixed in repository.
