### ISSUE TITLE
Btrfs snapshot rollback in grub

### ISSUE THREAD

**Issue by johnr14** [openSUSE/snapper#196]
It would be great to have a grub rollback feature.

I would recommend to merge (whole/part) of this tool in snapper :
https://github.com/Antynea/grub-btrfs

That way, you could revert quickly in case of a break without having to boot an usb disk to promote a snapshot to / then reboot.

Thanks

**Comment by aschnell** [comment]
Snapper can already be used for rollbacks, see http://snapper.io/2014/04/29/rollback.html.

In openSUSE grub2 is able to show a list of snapshots to the user and boot from a snapshot.

The planned support for custom script plugins, see https://github.com/openSUSE/snapper/issues/28, will AFAIS also allow to use grub-btrfs.
