### ISSUE TITLE
Snapper 0.2.8 won't build on RHEL 7 system

### ISSUE THREAD

**Issue by Shibby91** [openSUSE/snapper#202]
I am trying to build the latest version of snapper on a RHEL 7.1 system:

$ ./configure --prefix=/usr/local --disable-btrfs --disable-rollback && make

Make gets most of the way through but bombs out when building the installation-helper object file:
   ......
 CXXLD    installation-helper
installation-helper.o: In function `step3(std::string const&, std::string const&)':
/home/biscuit/snapper-0.2.8/client/installation-helper.cc:159: undefined reference to `snapper::Btrfs::Btrfs(std::string const&, std::string const&)'
/home/biscuit/snapper-0.2.8/client/installation-helper.cc:161: undefined reference to `snapper::Btrfs::addToFstab(std::string const&) const'
installation-helper.o: In function `~Btrfs':
/home/biscuit/snapper-0.2.8/client/../snapper/Btrfs.h:37: undefined reference to `vtable for snapper::Btrfs'

Any idea what is going on here? I disabled btrfs support but that doesn't appears to help.

**Comment by aschnell** [comment]
The client "installation-helper" needs btrfs enabled so it must be conditional in clients/Makefile.am. I will make a patch today.

**Comment by aschnell** [comment]
Fixed.
