### ISSUE TITLE
No XFS support?

### ISSUE THREAD

**Issue by Shibby91** [openSUSE/snapper#204]
I am trying to create a  configuration file with snapper version 0.2.8:

$  /var/tmp/snapper-0.2.8/client/snapper --version
snapper 0.2.8
flags no-btrfs,lvm,ext4,xattrs,no-rollback,no-btrfs-quota

When I run snapper with create-config I get an invalid filesystem error:

$ /var/tmp/snapper-0.2.8/client/snapper create-config --fstype="lvm(xfs)" /var/named
Creating config failed (invalid filesystem type).

Based on the following blurb in the manual page I would expect this to work:

"Manually set filesystem type. Supported values are btrfs, ext4 and lvm. For lvm, snapper uses LVM thin-provisioned snapshots. The filesystem type on top of LVM must be provided in parentheses, e.g. lvm(xfs)."

Here is the file system info:

/dev/mapper/vg_sysvg--00-lv_bind on /var/named type xfs (rw,nosuid,noexec,relatime,seclabel,attr2,inode64,logbsize=64k,sunit=128,swidth=128,noquota)

As well as the lvs info:

  LV       VG          Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  lv_bind  vg_sysvg-00 twi-aotz-- 100.00g             0.00   0.43            

Is XFS no longer supported?

**Comment by oniko** [comment]
On what LV do you have your filesystem? According to lvs output above the lv_bind is a thin pool not a thin provisioned LV

**Comment by oniko** [comment]
To explain it a little bit more:

Thin pool is a special type of LV all other thin LVs (including thin snapshots) allocate space from. Unfortunately mount is sometimes able to mount filesystem from a thin pool itself when it detects fs signature in a thin pool LV.

You have to mount the fs from thin LV. You can recognise thin LV type by capital letter v in lvs output, e.g.:

 thin_pool                 vg   twi-aotz-- 150.71g                                     48.88  27.09                           
 tmp                         vg   Vwi-a-tz-- 150.00g thin_pool                           6.86 

In this example thin pool is vg/thin_pool and thin provisioned LV is vg/tmp.

**Comment by oniko** [comment]
btw the mount issue with thin pool should be fixed since util-linux v2.25 and later

**Comment by Shibby91** [comment]
It looks like I missed the create thinpool step. Thanks for the feedback oniko.

**Comment by aschnell** [comment]
Thanks Ondrej for the quick analysis. Closing as invalid.
