### ISSUE TITLE
DBus::Marshalling has subclasses named Hihi and Hoho

### ISSUE THREAD

**Issue by Profpatsch** [openSUSE/snapper#219]
I had a big “wat”-moment.

https://github.com/openSUSE/snapper/blob/master/server/Types.h

**Comment by mvidner** [comment]
Oh. Er, um.
Apparently we should rename `Hoho` to `Marshaller` and `Hihi` to `Unmarshaller`.

**Comment by Profpatsch** [comment]
hehe. :)
