### ISSUE TITLE
Feature: Timeline snapshots only created if some change since last

### ISSUE THREAD

**Issue by jamespharvey20** [openSUSE/snapper#222]
I'd love to see the automatic timeline snapshots via the systemd snapper-timeline.timer only be created if there's a change since the last snapshot.  For example, if the most recent snapshot is number 93, it could perform a "snapper status 0..93" and only create the timer-caused snapshot 94 if there's differences.

It would be useful for non-root volumes that might not change often, such as /boot.  It would be very beneficial when using TIMELINE_CLEANUP, so changes are kept rather than being blown away by snapshots that are no different from each other.

I could see some people disliking this change, so perhaps as an option in the config file.

**Comment by aschnell** [comment]
Checking whether there have been changes to the filesystem is a slow and IO heavy operation so I do not like to do this every hour. Apart from that during the check the filesystem may again change so there is a race condition. So snapper would first have to create a new snapshot and then do the comparison against the previous snapshot.
