### ISSUE TITLE
snapper-timeline.timer is not creating snapshots or logs

### ISSUE THREAD

**Issue by gotnosocks** [openSUSE/snapper#227]
I have started and enabled snapper-timeline.timer and snapper-cleanup.timer, but my system is not creating any new timeline snapshots. If I run the command from snapper-timeline.timer as root,
`sudo /usr/lib/snapper/systemd-helper --timeline`, it executes and I see an entry in the snapshot table with Description and Cleanup equal to "timeline".

I'm running snapper-0.2.8-1.fc23.x86_64 on Fedora 23.

As I stated in the title the timer never creates a new snapshot or any logged events as far as I can tell. Any help would be much appreciated.

**Comment by gotnosocks** [comment]
I was able to resolve this issue by installing an selinux type enforcement (.te) policy from audit2allow 
with the following contents:

module snappertimelinetimer 1.0;

require {
        type init_t;
        type snapperd_t;
        class dbus send_msg;
}

#============= snapperd_t ==============
allow snapperd_t init_t:dbus send_msg;

**Comment by oniko** [comment]
Hi, could you please open Fedora bug for selinux targeted policy?

**Comment by oniko** [comment]
I believe this is (and if so) a bug in a policy and not in snapper. On the other hand there's long standing issue with btrfs and selinux with regard to subvolumes. I'll post pull request with patch for it later this week.

**Comment by oniko** [comment]
fedora bug on selinux-policy: https://bugzilla.redhat.com/show_bug.cgi?id=1323732

For the remaining issues with snapper and selinux I created pull request: https://github.com/openSUSE/snapper/pull/239

**Comment by aschnell** [comment]
PR #239 has been merged.
