### ISSUE TITLE
build fails with btrfs-progs 4.5

### ISSUE THREAD

**Issue by ShalokShalom** [openSUSE/snapper#231]
https://gist.github.com/ShalokShalom/3875bcd9740d3677cb5a183c4b05ab3e

**Comment by aschnell** [comment]
Looks like the btrfs include file ioctl.h uses the type u64 but does not take care that it is actually defined.

**Comment by oniko** [comment]
seems it got fixed with 4.5.1 release. (just had to reassure myself I didn't break it with my patch:))

**Comment by ShalokShalom** [comment]
yep, solved, thanks a lot, nice support :)

**Comment by ShalokShalom** [comment]
close
