### ISSUE TITLE
Failure (error.something).

### ISSUE THREAD

**Issue by stefanfritsch** [openSUSE/snapper#246]
Hi,

I always knew that snapper's error messages tended to be... not 100% optimal but this new one really takes the cake:

    [root@se-helmet mnt]# snapper -v create-config /mnt/test
    Failure (error.something).

How do I even start debugging that?

I'm trying to create a config in an archlinux container. The only message I can find is dbus telling me that it successfully activated service 'org.opensuse.Snapper'.

Thx
Stefan

**Comment by aschnell** [comment]
That is indeed a bad error message: It means that an generic exception was thrown.

First you should look at /var/log/snapper.log. If that does not help you can start snapperd
within gdb, catch throws and then see the backtrace.

**Comment by aschnell** [comment]
I cannot help without further information.
