### ISSUE TITLE
Tag new releases

### ISSUE THREAD

**Issue by mtorromeo** [openSUSE/snapper#247]
Hi,
I maintain the snapper package on Arch Linux.

Please start tracking snapper versions with git tags again.
The last tagged version on GitHub is 0.2.8 but we are now at 0.3.2. I failed to track new releases because I didn't see any new tag.

This was already a problem some time ago (see #11) and even without tags, there is no release source tarball on ftp://ftp.suse.com/pub/projects/snapper/ for any version after 0.2.8.

Thanks!

**Comment by aschnell** [comment]
We automated some steps of packaging snapper but unfortunately tagging and uploading a tarball are missing. I will do so manually soon.

**Comment by aschnell** [comment]
I have increased the version to 0.3.3 and also tagged it.

**Comment by oniko** [comment]
Thank you!
