### ISSUE TITLE
snapperd: abrtd detects error when snapperd finishes running on debug mode

### ISSUE THREAD

**Issue by oniko** [openSUSE/snapper#256]
Hi Arvin,

originally reported in https://bugzilla.redhat.com/show_bug.cgi?id=1357010 but I can easily reproduce it also with current 0.3.3.

There's clash between lifetime of static mutex in simple_log_do() and global Backgrounds object. It happens only when daemon is shutting down and it was started with -d argument in debug mode. Also you have to create workload with at least single background job so that y2deb("worker interrupted") is hit during Backgrounds destruction to reproduce it.

I'm not too familiar with C++ std, but so far I haven't figured out different bulletproof solution than removing the y2deb() call from the Backgrounds worker. Which is not optimal since we'd like to know that someone or something has interrupted one of snapperd threads. All other solution I tried are undefined by the c++ standard:/

Anyway I'll let you know If I come with saner patch other than the one deleting the debug message...

**Comment by oniko** [comment]
Feel free to use it or discard it, as usual. I'm not sure there is a better solution while taking into consideration global objects in various translation units... I found myself in 'undefined behaviour' territory with every other attempts I made.

Kind regards
O.

**Comment by aschnell** [comment]
Merged #258 to fix issue.
