### ISSUE TITLE
Setting a minimum free disk space cleanup value

### ISSUE THREAD

**Issue by paskalito** [openSUSE/snapper#266]
snapper should definitely have a feature like this:

https://github.com/paskalito/btrfs-snapper-snapshot-overflow-rescuer-scriptt

would be nice in the config if you could set a value on how less free diskspace it should start to delete old snapshots regardless of all other options. - because otherwise it will simply break your system.

**Comment by aschnell** [comment]
Space aware cleanup is implemented already, see http://snapper.io/2016/05/18/space-aware-cleanup.html.
