### ISSUE TITLE
Maximum description length for snapper

### ISSUE THREAD

**Issue by NicoHood** [openSUSE/snapper#268]
If you call `snapper list` and have snapshots with a very long description it will produce an unreadable table. This bug was noticed with the pacman hooks of snap-pac: https://github.com/wesbarnett/snap-pac/issues/4

It would be nice to cut off the table at a maximum number/terminal width and use `--full` for the full output if desired.

**Comment by kmotavalli** [comment]
https://github.com/kmotavalli/snapper-1/pull/3/commits

something like this?

**Comment by aschnell** [comment]
With https://github.com/openSUSE/snapper/pull/612 there is a new option ```--abbreviate```. It is not the default yet.
