### ISSUE TITLE
Build fails on Fedora 24

### ISSUE THREAD

**Issue by fholzer** [openSUSE/snapper#273]
I fixed the spec file in my branch but `cmp-lt.test` fails: https://build.opensuse.org/package/rdiff/home:ferdinandh:branches:filesystems:snapper/snapper?linkrev=base&rev=2
https://build.opensuse.org/package/live_build_log/home:ferdinandh:branches:filesystems:snapper/snapper/Fedora_24/x86_64
Not sure how to proceed. Seems like an issue with the locales, but i don't know how to fix or investigate it.

Also, local build fails because of
````
Obsoletes:      %(echo `seq -s " " -f "libsnapper%.f" $((3 - 1))`)
````
but i think that's an issue with osc or some rpm-related tool.

**Comment by aschnell** [comment]
Thanks, I have included the spec-file changes.

**Comment by aschnell** [comment]
The failure in cmp-lt.test is due to missing locales. I added glibc-langpack-en and glibc-langpack-de, see https://github.com/openSUSE/snapper/pull/276/commits/21591f4ef4ea67796b0cf0da6e565ad111425943.

This is explained in https://fedoraproject.org/wiki/Changes/Glibc_locale_subpackaging.

**Comment by aschnell** [comment]
Builds now for Fedora 24.
