### ISSUE TITLE
info.xml permissions

### ISSUE THREAD

**Issue by NicoHood** [openSUSE/snapper#279]
To me it seems that info.xml has wrong permissions (root:root 600). This means only root can read the file. However the snapshots themself are permissions root:root 755. And on top of that normally the snapshot folder is protected by root:root 750, so nobody should be able to enter the directory anyways.

Now I've set the group to wheel on archlinux which gives my admin user access to the snapshots of root and the group users is used for /home. So a normal user can access the /home history. Everything except that info.xml file is readable. Its quite anying to copy this file. It would be better to create it with permission root:root 664.

The file is possibly created here, but I am not 100% sure:
https://github.com/openSUSE/snapper/blob/aa4b358326b11673749c06a04001cb9ec680934d/snapper/Snapshot.cc#L425

https://github.com/openSUSE/snapper/blob/master/snapper/XmlFile.cc#L66

https://github.com/openSUSE/snapper/blob/aa4b358326b11673749c06a04001cb9ec680934d/snapper/FileUtils.cc#L359

**Comment by matejdro** [comment]
Have you found a workaround for this issue?

**Comment by NicoHood** [comment]
Nope, did not work on that. I dont even know if the issue still exists, but I guess so?

**Comment by matejdro** [comment]
Yes, it still exists (I wanted to expose my history via sshfs, so I can check out history from anywhere without sudoing into server. But this prevents my idea).

**Comment by ajgringo619** [comment]
I had figured that the permissions/ACLs would match the /.snapshots directory.

**Comment by CHN-beta** [comment]
I have tried this patch:

```
diff --git a/snapper/FileUtils.cc b/snapper/FileUtils.cc
index 9da572f..48f60fa 100644
--- a/snapper/FileUtils.cc
+++ b/snapper/FileUtils.cc
@@ -424,7 +424,7 @@ namespace snapper
 		v /= 62;
 	    }
 
-	    int fd = open(name, O_RDWR | O_CREAT | O_EXCL | O_CLOEXEC, S_IRUSR | S_IWUSR);
+	    int fd = open(name, O_RDWR | O_CREAT | O_EXCL | O_CLOEXEC, S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH);
 	    if (fd >= 0)
 		return fd;
 	    else if (errno != EEXIST)
```
After that, the permission of info.xml become 640. No idea why `S_IROTH` does not work.

**Comment by aschnell** [comment]
The permissions are now relax by PR #830.
