### ISSUE TITLE
snapper list command shows a bit ugly table under (at least) ja_JP locale.

### ISSUE THREAD

**Issue by henrich** [openSUSE/snapper#280]
correct:
![8c2a31ad-1328-32a1-1daf-472f7055e478](https://cloud.githubusercontent.com/assets/619392/19224656/46a784a6-8ec5-11e6-996b-42c2ecb85a77.png)

wrong (under ja_JP locale):
![eabf27ee-a9d0-4430-db19-63b894dae640](https://cloud.githubusercontent.com/assets/619392/19224644/1ccc1476-8ec5-11e6-93ee-3e91b45d1cb6.png)

number 0 line is wrong.

**Comment by aschnell** [comment]
Looks like https://github.com/openSUSE/snapper/issues/245.
