### ISSUE TITLE
Snapper & apt-btrfs-snapshot on Ubuntu

### ISSUE THREAD

**Issue by badarotti** [openSUSE/snapper#287]
Hi.

I'm using Snapper 0.2.4 on Ubuntu Server 16.04. It works fine but there is no provision to take snapshots before and after system changes like it does on OpenSUSE/Yast/Zypper. 

I installed apt-btrfs-snapshot and it takes snapshots before using the package manager but its snapshots are not visible to or can be managed by Snapper. I understand that each application does it's own thing but is there a way to integrate them and have them work like OpenSUSE?

Thanks

**Comment by NicoHood** [comment]
You can also have a look at snap-pac for archlinux:
https://github.com/wesbarnett/snap-pac

**Comment by badarotti** [comment]
Thanks, I'll look into it.

**Comment by darkdragon-001** [comment]
On **Ubuntu**, `apt` sources scripts in `/etc/apt/apt.conf.d/`. The following is used for [`apt-btrfs-snapshot`](https://bazaar.launchpad.net/~mvo/apt-btrfs-snapshot/trunk/view/head:/data/80-btrfs-snapshot):

    DPkg::Pre-Invoke {"if [ -x /usr/bin/apt-btrfs-snapshot ] && apt-btrfs-snapshot supported; then apt-btrfs-snapshot snapshot; fi "; };

Would be nice if someone would package this as a Debian package (`deb`).

---

On **Fedora**, there is a [DNF snapper Plugin](https://dnf-plugins-extras.readthedocs.io/en/latest/snapper.html) for their package manager `dnf`.

---

> @aschnell: I'm not aware of a ready solution here. If apt supports plugins/hooks it might be possible to make apt call snapper. This is the way it works on openSUSE, see https://github.com/openSUSE/snapper/blob/master/scripts/zypp-plugin.py.

For **SUSE**, `zypper` plugin is removed in https://github.com/openSUSE/snapper/commit/3b1ebafa6b389798a9b25c56146635a563159358.

**Comment by aschnell** [comment]
The zypper plugin was rewritten in C++ to reduce dependencies. It is now at https://github.com/openSUSE/snapper/tree/master/zypp-plugin.
