### ISSUE TITLE
Not able to login with 12char length username and password

### ISSUE THREAD

**Issue by Rohini-Chahar** [openSUSE/snapper#312]
Hi,

I am not able to login via dropbear when my username and password consists of 12chars or more. 
Not sure what is the reason but when tried to put some logs in code flow got to know flow is not getting completed for pty-req and function where this is getting stuck is:
sessionpty(chansess);  - - > pty_setowner - - > getgrnam. getgrnam is being called with option tty. After this function call no logs are coming. 
For shorter length users things are working fine.
Please suggest.

Regards,
Rohini

**Comment by mvidner** [comment]
Uh, I don't see how this problem is related to Snapper. Sure this is not misfiled?

**Comment by aschnell** [comment]
I also do not see how this problem is related to snapper.
