### ISSUE TITLE
Enhancement: Json output for Snapper

### ISSUE THREAD

**Issue by ericpulvino** [openSUSE/snapper#313]
Not sure if I'm filing this in the right place... sorry in advance.

Having Snapper output in JSON would simplify automated control of snapper and remove the need to screen-scrape.

**Comment by devurandom** [comment]
It seems this was implemented in version 0.8.6: http://snapper.io/2019/11/06/machine-readable-output.html

**Comment by aschnell** [comment]
Implemented by https://github.com/openSUSE/snapper/pull/494.
