### ISSUE TITLE
Snapper list columns get wonky by unicode letters in dates

### ISSUE THREAD

**Issue by etu** [openSUSE/snapper#314]
OS: Archlinux, latest stable.

```
 etu  phouchg  ~  $  snapper --version
snapper 0.4.1
flags btrfs,lvm,ext4,xattrs,rollback,btrfs-quota,no-selinux
```

Here's a screenshot of the list:
![2017-01-05-101255_1206x604_scrot](https://cloud.githubusercontent.com/assets/461970/21674796/aa75abda-d32f-11e6-8241-e4726304b9de.png)
Here's a screenshot of my locales:
![2017-01-05-101316_403x376_scrot](https://cloud.githubusercontent.com/assets/461970/21674806/b4fab7b2-d32f-11e6-8d83-07fbcca90456.png)

This is not a new issue for me, it's been around since I started using snapper. Just that I didn't get around to reporting it.

**Comment by NicoHood** [comment]
Duplicate of https://github.com/openSUSE/snapper/issues/245

**Comment by etu** [comment]
Oh well then
