### ISSUE TITLE
Remove btrfs quota qgroup after deleting BTRFS snapshot in Snapper

### ISSUE THREAD

**Issue by MurzNN** [openSUSE/snapper#325]
We have the problem with snapper and btrfs snapshots on btrfs quota enabled storage: when btrfs delete snapshot - it don't delete qgroup for this snapshot, so after deleting snapshot via snapper - we god wrong quota counts in disks.

Here is documentation about this: https://btrfs.wiki.kernel.org/index.php/Quota_support

>  Using btrfs subvolume delete will break qgroup unshared space usage.
After deleting a subvolume, you must manually delete the associated qgroup. 

Please add to snapper checking if btrfs quota enabled and if yes - remove qgroup after deleting snapshot.

**Comment by MurzNN** [comment]
Here is kernel bug threads about this: 

- https://bugzilla.kernel.org/show_bug.cgi?id=91751
- https://bugzilla.kernel.org/show_bug.cgi?id=61951

And here is same bug in other script https://github.com/digint/btrbk/issues/49

**Comment by aschnell** [comment]
There is code to delete the qgroup: https://github.com/openSUSE/snapper/blob/master/snapper/Btrfs.cc#L411

Is your snapper build with quota support?

**Comment by MurzNN** [comment]
Thanks, good to hear that this is already implemented! Btrfs have quota support, because I can work with quota via commands. But I have use too old version of snapper (0.1.8) seems this feature is missed in this version, so I try to upgrade and recheck. In which version this is implemented at first time?

**Comment by aschnell** [comment]
Likely with the space aware cleanup in version 0.3.0 (2016-04-06).
