### ISSUE TITLE
[Feature request] Display used space via quota to btrfs snapshots for snapper list command

### ISSUE THREAD

**Issue by MurzNN** [openSUSE/snapper#326]
At now BTRFS already have support for quota qgroups and easy way to check total and used size of snapshots, so will be good to integrate this in `snapper list` report.

We can check if btrfs quota is enabled via `btrfs qgroup show --raw /path/to/btrfs` command and get bytes of total size (rfer) and unshared size (disk space usage) for each btrfs volume (subvolume and snapshot) by volume id.

And if quota is enabled and data exists - we can display this quotas  (`Total size` and `Space used`) via comparing volume id in `snapper list` table output.

**Comment by aschnell** [comment]
Meanwhile snapper can show the exclusive space, see http://snapper.io/2018/10/04/used-space.html.

I do not see the shared space are so useful.
