### ISSUE TITLE
0.4.2 deb broke planned snapshots/cleanups

### ISSUE THREAD

**Issue by petchema** [openSUSE/snapper#328]
Since 0.4.2 cronfiles have been renamed from /etc/cron.{hourly,daily}/snapper to /etc/cron.{hourly,daily}/snapper/suse.de-snapper
But Debian's run-parts do not pick scripts recursively, so they stopped working
(Tested on Linux Mint)

**Comment by aschnell** [comment]
Should be fixed by https://github.com/openSUSE/snapper/pull/329.
