### ISSUE TITLE
'root' config mandatory in centos 7?

### ISSUE THREAD

**Issue by fbafkis** [openSUSE/snapper#333]
Hi, I have installed snapper in Centos 7 following the instruction (adding the repo and then using yum) . I configured a pair of snapshot schedule (configs). The volume where the system is installed, is formatted in ext4 format, and the storage hard drives are btrfs. They have few subvolumes. I tried to create configs for the subvolumes (mounted in mnt/... ) but if I try to give the "snapper list" command I receive the error message "'root' config not found. It' likely snapper isn't configured yet. Check man snapper for more infos", or something very similar. But I can't create the config for the / volume because it is not btrfs. I tried to give a subvolume path to the 'root' config and then everything works, but I don't want to be forced to create a 'root' named config to use snapper. Any suggestion? 

Thank you!

**Comment by aschnell** [comment]
If you do not specify which config to use snapper uses 'root'. Use 'snapper list-configs' and then e.g. 'snapper -c <config-name> list'.

**Comment by aschnell** [comment]
I assume the issue is resolved.
