### ISSUE TITLE
Fix URL on the main page snapper.io

### ISSUE THREAD

**Issue by uvsmtid** [openSUSE/snapper#335]
If you click on the top video on [snapper.io](http://snapper.io), you get **[this link](https://www.youtube.com/v/9H7e6BcI5Fo?start=209)**:
```
https://www.youtube.com/v/9H7e6BcI5Fo?start=209
```
Which is `HTTP ERROR 404`-broken.

At the same time, if you go to the [videos page](http://snapper.io/videos.html) the **[link is fixed](http://www.youtube.com/watch?v=9H7e6BcI5Fo&t=3m29s)**:
```
http://www.youtube.com/watch?v=9H7e6BcI5Fo&t=3m29s
```

Please fix it on the main page.

**Comment by sielicki** [comment]
https://github.com/openSUSE/snapper/pull/339

**Comment by aschnell** [comment]
Thanks for the patch.
