### ISSUE TITLE
How to disable creating hourly snapshots  and stay only daily in Snapper btrfs snapshot tool?

### ISSUE THREAD

**Issue by MurzNN** [openSUSE/snapper#340]
I need to do only daily snapshots of some btrfs volumes. So I set in config file:
`TIMELINE_LIMIT_HOURLY="0"`
But snapper continue create new snapshots every hour and cleanups it every day only on cron.daily task.

How can I totally disable creating hourly snapshots on specific config files and stay only daily snapshots?

**Comment by MurzNN** [comment]
Same question is for create only weekly and monthly snapshots. 
I can move manually file `/etc/cron.hourly/snapper` to `/etc/cron.daily/snapper` or `/etc/cron.weekly/snapper`, but this disable hourly backups globally for all configs.

Will be good to look at the `TIMELINE_LIMIT_HOURLY` value and if it equal 0 - skip creating hourly snapshot, and same rule for daily, weekly, mothly.

**Comment by aschnell** [comment]
You will have to modify the cron or systemd config.

**Comment by MurzNN** [comment]
Can you provide some examples how to do this? And will be good to have build-in functional for solve described tasks in future versions.
