### ISSUE TITLE
Unable to build due to a failed exsl import

### ISSUE THREAD

**Issue by BartWillems** [openSUSE/snapper#342]
[This file](https://github.com/openSUSE/snapper/blob/master/doc/manpages.xsl#L3) tries to import "http://exslt.org/common", but this results in a 404.

I tried to contact the owners of the file, but their contact page also results in a 404...
http://exslt.org/exsl/index.html

**Comment by aschnell** [comment]
For me it still works but this is likely due to all required docbook stylesheets being installed locally.

Anyway, isn't this a bug in docbook instead of snapper?

**Comment by BartWillems** [comment]
I don't know docbook, so I was under the assumption that it was a part of snapper.
I'll close this issue then.
