### ISSUE TITLE
Samba: vfs objects = snapper on Debian 8.7

### ISSUE THREAD

**Issue by obrobertsen** [openSUSE/snapper#343]
I am using Debian and BTRFS on a separate /data filesystem.
Currently using manual scripting for creating snapshot in /data/.snapshot with format @GMT_$(date +%Y.%m.%d-%H.%M.%S)
In /etc/samba/smb.conf i have vfs objects = shadow_copy2
And previous version is working great from Windows 10 client.

With vfs objects = snapper
I was hopeing i could use snapper tool and then previous version from Win 10
But is this tested on Debian 8.7

For me it is not working.
Do I need to compile snapper.so

**Comment by ddiss** [comment]
Thanks for the report. Yes, Samba needs to be built with the snapper VFS module enabled, which is done by default if the dbus development libraries are present at configure time.
you should be able to check this with "smbd -b |grep snapper"

**Comment by obrobertsen** [comment]
**How to get the snapper VFS module installed on standard Debian 8.7**

# man vfs_snapper 
< is working>

# cat /etc/debian_version
8.7

# smbd -b |grep vfs_
 vfs_acl_tdb_init
   vfs_acl_xattr_init
   vfs_aio_fork_init
   vfs_aio_linux_init
   vfs_aio_posix_init
   vfs_aio_pthread_init
   vfs_audit_init
   vfs_btrfs_init
   vfs_cap_init
   vfs_catia_init
   vfs_commit_init
   vfs_crossrename_init
   vfs_default_quota_init
   vfs_dfs_samba4_init
   vfs_dirsort_init
   vfs_expand_msdfs_init
   vfs_extd_audit_init
   vfs_fake_perms_init
   vfs_fileid_init
   vfs_fruit_init
   vfs_full_audit_init
   vfs_linux_xfs_sgid_init
   vfs_media_harmony_init
   vfs_netatalk_init
   vfs_posix_eadb_init
   vfs_preopen_init
   vfs_readahead_init
   vfs_readonly_init
   vfs_recycle_init
   vfs_scannedonly_init
   vfs_shadow_copy2_init
   vfs_shadow_copy_init
   vfs_smb_traffic_analyzer_init
   vfs_streams_depot_init
   vfs_streams_xattr_init
   vfs_syncops_init
   vfs_time_audit_init
   vfs_worm_init
   vfs_xattr_tdb_init
   vfs_posixacl pdb_smbpasswd pdb_tdbsam pdb_wbc_sam auth_sam auth_unix auth_winbind auth_wbc auth_domain auth_builtin vfs_default nss_info_template idmap_tdb idmap_passdb idmap_nss pdb_samba_dsdb pdb_ldapsam

**Comment by ddiss** [comment]
> How to get the snapper VFS module installed on standard Debian 8.7

This is something that you need to take up with the downstream Debian Samba packagers. For now, I'd suggest that you continue to use vfs_shadow_copy2 alongside snapper.

@aschnell I think this bug can be closed as a downstream packaging issue.

**Comment by ddiss** [comment]
@obrobertsen please do follow up with the Debian packagers via https://www.debian.org/Bugs/Reporting . It'd be great if they could include Samba's vfs_snapper in their next release.
