### ISSUE TITLE
Snapper is broken due to dependency on dbus (dbus fatal exception)

### ISSUE THREAD

**Issue by zetok** [openSUSE/snapper#344]
![spectacle ym1279](https://cloud.githubusercontent.com/assets/3148759/25662256/cb249a7e-300b-11e7-93ab-c265755c80b3.png)

What is even the point of this project when it's designed to fail at the very moment that it ought to work?

**Comment by aschnell** [comment]
Try --no-dbus option. Works meanwhile with every snapper command.

**Comment by aschnell** [comment]
Also see http://snapper.io/2016/12/19/no-dbus-for-all.html.
