### ISSUE TITLE
Multiple Shares with Samba VFS module

### ISSUE THREAD

**Issue by DocMAX** [openSUSE/snapper#349]
I try to have 2 shares with shadow copy options in Windows.

path = /
path = /folder1/folder2

I did a "snapper -c root create-config /" which works with vfs snapper (btrfs subvolume exists)
But doing a "snapper -c folder2 create-config /folder1/folder2" doesn't work (error: E/A Error)

How can i accomplish what i want?

**Comment by aschnell** [comment]
Maybe /folder1/folder2 is not a btrfs subvolume.

**Comment by aschnell** [comment]
No feedback.
