### ISSUE TITLE
Thank you so much for documenting your travis/docker build setup thoroughly!

### ISSUE THREAD

**Issue by JLLeitschuh** [openSUSE/snapper#363]
Not an issue, this is a thank you. (I know this is kind of unusual)

I just want to thank you for having such a well documented Docker/Travis build configuration that was incredibly easy to follow.

I needed to harness a project to run a JavaFX application built with gradle inside of a Ubuntu 16.2 Docker image and your project was the inspiration that helped me down the right path to solving this problem.

The result of this work is here https://github.com/wpilibsuite/shuffleboard/pull/220 I mentioned that this project was what inspired our solution.

Thank you again, and please allow me to show myself out.

**Comment by aschnell** [comment]
Thanks.

**Comment by kobliha** [comment]
Thanks for such a great feedback :)
