### ISSUE TITLE
Please push tags (0.5.1, 0.5.2 and 0.5.3 are missing)

### ISSUE THREAD

**Issue by henrich** [openSUSE/snapper#364]
It seems that 0.5.1 and 0.5.2 was not tagged (or not pushed to repo).

**Comment by NicoHood** [comment]
@aschnell Any chance to get the tag on github? Also what about GPG signed releases (#295 )?

**Comment by henrich** [comment]
Only openSUSE has snapper-0.5.3.tar.bz2 tarball. 
see https://build.opensuse.org/package/show/filesystems/snapper

@aschnell : push tags to repo is hard? Or because of distributions except openSUSE are second-class citizen, so ignoring?

**Comment by henrich** [comment]
Okay, 0.5.4 was pushed, thanks.
