### ISSUE TITLE
--help option whit an error

### ISSUE THREAD

**Issue by frecio231** [openSUSE/snapper#367]
Hello, I'm presenting a problem, the "snnaper --help" on the "diff" section says that you need to use it like "snapper diff 2 3" but the correct and the one that says the error at running like that is "snapper diff 2..3" so, hope you can correct this little error so not more people get confused. Also the man says correctly but for rapid help is quite convenient to be correct on the "--help"

**Comment by aschnell** [comment]
Are you referring to the Spanish translation (https://github.com/openSUSE/snapper/blob/master/po/es.po#L166)?

**Comment by frecio231** [comment]
Actually yes, that.

**Comment by aschnell** [comment]
Fixed in https://github.com/openSUSE/snapper/commit/962051a31a651c542af4ced7741fdf644329fe2f.

In general translations can be improved by anyone at https://l10n.opensuse.org/projects/snapper/.
