### ISSUE TITLE
Creating config manually

### ISSUE THREAD

**Issue by rightaway** [openSUSE/snapper#369]
Instead of using the `create-config` command, if I edit `/etc/conf.d/snapper` and add the config file under `/etc/snapper/configs/home`, I get an error when trying to take a snapshot `IO Error (open failed path:/home errno:2 (No such file or directory))`. It works fine when I create the `home` config using the command. But how can I do so manually?

I'd like to provision a system with an existing set of configuration, so I'd like to know how to restore an existing snapper setup.

**Comment by MountainX** [comment]
There are three steps:
1. create a subvolume .snapshots manually
2. edit `SNAPPER_CONFIGS=""` in the config file (found at /etc/default/snapper or /etc/conf.d/snapper). Example: `SNAPPER_CONFIGS="home"`
3. create your volume config such as `/etc/snapper/configs/home`. The name of this file must match with the name of the config you created in the above step. In this example, both are `home`. If the names do not match, snapper ignores the config.
