### ISSUE TITLE
Config creation fails with "already exists"

### ISSUE THREAD

**Issue by thiagomacieira** [openSUSE/snapper#371]
Possibly related to #139.

Previous state showing that there's no other configuration besides "root":

```
# snapper list-configs
Config | Subvolume
-------+----------
root   | /        
# ls /etc/snapper/configs
root
# grep CONFIGS /etc/sysconfig/snapper 
SNAPPER_CONFIGS="root"
```

The btrfs subvolume does exist:

```
# grep /mnt/data /etc/mtab 
/dev/vda2 /mnt/data btrfs rw,relatime,space_cache,subvolid=275,subvol=/@/mnt/data 0 0
```

But creating the config fails:
```
# snapper -v create-config /mnt/data
Creating config failed (config already exists).
```

snapper.log logs the following:
```
2017-11-19 09:57:31 MIL libsnapper(81182) Snapper.cc(createConfig):310 - Snapper create-config
2017-11-19 09:57:31 MIL libsnapper(81182) Snapper.cc(createConfig):311 - libsnapper version 0.5.0
2017-11-19 09:57:31 MIL libsnapper(81182) Snapper.cc(createConfig):313 - config_name:root subvolume:/mnt/data fstype:btrfs template_name:default
2017-11-19 09:57:31 MIL libsnapper(81182) Snapper.cc(getConfigs):269 - Snapper get-configs
2017-11-19 09:57:31 MIL libsnapper(81182) Snapper.cc(getConfigs):270 - libsnapper version 0.5.0
2017-11-19 09:57:31 MIL libsnapper(81182) AsciiFile.cc(reload):114 - loading file /etc/sysconfig/snapper
2017-11-19 09:57:31 MIL libsnapper(81182) AsciiFile.cc(getValue):235 - key:SNAPPER_CONFIGS value:root
2017-11-19 09:57:31 MIL libsnapper(81182) AsciiFile.cc(reload):114 - loading file /etc/snapper/configs/root
2017-11-19 09:57:31 MIL libsnapper(81182) AsciiFile.cc(getValue):235 - key:SUBVOLUME value:/
2017-11-19 09:57:31 MIL libsnapper(81182) AsciiFile.cc(reload):114 - loading file /etc/sysconfig/snapper
2017-11-19 09:57:31 MIL libsnapper(81182) AsciiFile.cc(getValue):235 - key:SNAPPER_CONFIGS value:root
2017-11-19 09:57:31 WAR libsnapper(81182) Snapper.cc(createConfig):360 - THROW: config already exists
2017-11-19 09:57:31 WAR libsnapper(81182) Client.cc(dispatch):1556 - CAUGHT: config already exists
```

I have no idea how to debug this further.

**Comment by thiagomacieira** [comment]
Nowhere in the documentation does it say the command should be:

    snapper -c data create-config /mnt/data

**Comment by aschnell** [comment]
The snapper man page explains the -c option and the FAQ has examples.

**Comment by rtomaszewski** [comment]
the selection of options is somehow confusing when you create new config. I run into this error as well. After reading the man page I was still confused. Based on the info above the command I needed was 

 snapper --config bin  create-config -t rado /receive/@/bin

A suggestion, I think it would be a much simpler if the actual command to run would be:

**snapper create-config -t rado /recive/@/bin**   # uses the name of the subvolume to create the config file 

or

**snapper create-config -t rado /recive/@/bin  bin-config**  # you name the config you want

The order of the options is kind of identical to how you create snapshots in btrfs. 
It follows he logic of some other commands as well, like cp: cp <src> <dst> etc.

**Comment by brookst** [comment]
In case anyone else comes across this error:  
Snapper stores config files in the `/etc/snapper/configs` folder. However, deleting these config files doesn't make Snapper forget about them. They are remembered in the `/etc/default/snapper` file, in the `SNAPPER_CONFIGS` variable. If you clear out any remnant config names from there, you can then recreate them using `sudo snapper -c <data> create-config <data/path>`.

**Comment by nemonein** [comment]
@brookst and for others.
`# snapper -c name delete-config` just works.

**Comment by MasterCATZ** [comment]
Creating config failed (creating btrfs subvolume .snapshots failed since it already exists).

how woud I go about getting snapper working again with drives that were setup in the last install , 
fresh OS install but snapshots are not working

**Comment by kevinseelbach** [comment]
> Creating config failed (creating btrfs subvolume .snapshots failed since it already exists).
> 
> how woud I go about getting snapper working again with drives that were setup in the last install , fresh OS install but snapshots are not working

For anyone still having issues with this in 2023... I found that I had to delete the `.snapshots` subvolume and remove the offending configs from the `SNAPPER_CONFIGS` variable in `/etc/conf.d/snapper`, in order to re-create a config. This was an issue when I generated a few configs and immediately wanted to make a change.

If you don't care about your snapshots/data, this is what I ran to fix it... if anyone finds this later 


    # Delete the old snapshots, should be empty if this is a brand new config
    sudo btrfs subvolume delete /path/to/disk/.snapshots

    # remove your config name from the SNAPPER_CONFIGS list
    sudo sed -i 's/OLD_CONFIG_NAME//g' /etc/conf.d/snapper

    # generate your new configs 
    sudo snapper -c newconfig create-config -t yourtemplate /path/to/disk

**Comment by ezxpro** [comment]
@kevinseelbach coming across this answer in 2024 was such a blessing. I was about to bang my head against a wall because snappper friggin' didn't  know I don't have any configs anymore.

I also think that @aschnell should take a look into this because this is definitely a bug. If you don't delete the configuration from snapper itself of if somehow they get messed up and you need to recreate them, this little problem will drive you nuts.

Snapper should rely on `/etc/snapper/configs`, and if it doesn't find anything there, it should allow you to create any configuration you want.
