### ISSUE TITLE
systemd-helper skips remaining configs if one config throws error

### ISSUE THREAD

**Issue by SeeSpotRun** [openSUSE/snapper#382]
Maybe this is desired behavior but I had a recent scare when my root snapshots stopped working after one of the less important configs stopped working due to a permissions error.

I'm thinking maybe a `try... catch` somewhere around https://github.com/openSUSE/snapper/blob/5d50934e12dc9a5b2f197cfcf367a14d1cc55c95/client/systemd-helper.cc#L46-L48 might be all that's required.

I'd do a PR but my c++ is pretty limited.

**Comment by aschnell** [comment]
Indeed, the error handling should be improved.

**Comment by aschnell** [comment]
Thanks for the patch. I have improved it (#385) to also cover the cleanup functions and provide a overall exit status.

**Comment by SeeSpotRun** [comment]
Thanks, that's nicer.  Told you my c++ was carp.
