### ISSUE TITLE
Automatically delete Pre-Post YaST2 snapshots, if there were no user's modifications

### ISSUE THREAD

**Issue by MikhailKasimov** [openSUSE/snapper#399]
Hello!

On ```USE_SNAPPER=yes``` parameter in ```/etc/sysconfig/yast2``` I can easily overload disk-space by continuously doing ```open->close->open-close->open->...->close``` scheme with YaST2: Snapper honestly creates Pre-post pair for each YaST2 session, but what the sense of it, if no modifications were done by user? Snapper generates "empty" useless YaST2 Pre-post snapshots in such case.

I'm requesting some parameter for Snapper (or ```/etc/sysconfig/yast2```), such like ```DELETE_EMPTY_SNAPSHOTS="yes|no"```, which will automatically delete such "empty" YaST2 Pre-post snapshots, if there no modifications were made by user.

So, the idea is to create YaST2 Pre-post snapshots only, when user made change(-s) via YaST2.

Schematically, it can be like this algo:

1. Take Pre-1 Snapshot.
2. Calculate Pre-1 Snapshot Checksum and save it.
3. Take Post-2 snapshot.
4. Calculate Post-2 Snapshot Checksum and save it.
5. Compare (Pre-1 Snapshot Checksum) AND (Post-2 Snapshot Checksum).
6. If (Pre-1 Snapshot Checksum) = (Post-2 Snapshot Checksum), then delete (Pre-1 AND Post-2).
7. Else save Pre-1->Post2 snapshot pair and display it in snapshots list.

Thanks!

**Comment by aschnell** [comment]
snapper deletes empty pre-post-pairs once a day.
