### ISSUE TITLE
Link failure when building without btrfs support

### ISSUE THREAD

**Issue by GreatEmerald** [openSUSE/snapper#401]
Trying to build snapper 0.5.4 with `--disable-btrfs --enable-rollback --enable-ext4` results in a link failure:

```
libtool: link: x86_64-pc-linux-gnu-g++ -O2 -pipe -march=native -mindirect-branch=thunk -mfunction-return=thunk -std=c++11 -Wall -Wextra -Wformat=2 -Wnon-virtual-dtor -Wno-unused-parameter -Wl,-O1 -Wl,--as-needed -o .libs/List List.o  ../../snapper/.libs/libsnapper.so -lboost_thread -lboost_system -lxml2 -lacl -lz -lmount
../../snapper/.libs/libsnapper.so: undefined reference to `typeinfo for snapper::Btrfs'
../../snapper/.libs/libsnapper.so: undefined reference to `snapper::BtrfsUtils::qgroup_create(int, unsigned long)'
```
...and so on (full log: https://paste.pound-python.org/show/DrZ2jONoS0xNdpbDTGDP/)

As I understand it, `--disable-btrfs --enable-rollback` are mutually incompatible, but in that case I'd expect the build system to not allow setting them together.

Also, in the log you can see a line that says `checking for chsnap... /sbin/chsnap`, which is false: there is no `/sbin/chsnap` in my system. That is another build system oddity.

**Comment by devtote** [comment]
This error has persisted for years. Does anyone even knows what is chsnap?

**Comment by aschnell** [comment]
https://github.com/openSUSE/snapper/pull/607 fixes the problem.
