### ISSUE TITLE
default owndership for .snapshot directory

### ISSUE THREAD

**Issue by rickysarraf** [openSUSE/snapper#416]
Are there any recommendations upstream has for normal users are supposed to access their snapshots through `snapper` ?

Currently, creating a snapshot for a sub-volume, as a normal user is doable once the user sets the users in the config file. But further actions, such as `diff` etc do not work because `.snapshots` is set ownership `root:root` with permissions `0750`. This further creates problems for wrapper GUIs, because by this design, the user needs to run the GUI application as `root`. Something highly discouraged by all major distributions.

I'm assuming YaST does it as a `root`-only appilcation.

Do you think setting `.snaphosts` as `root;snapper` would be better ? That way, interested users could simply be part of the group and seamlessly be able to access their data. The drawback I see is that users from the common group have access to each other's data.

**Comment by aschnell** [comment]
The permissions can be solved using ACLs, see http://snapper.io/2014/01/30/sync-acl.html.

**Comment by rickysarraf** [comment]
Thank you for the quick reply. I went and checked the `snapper` manpage and it is documented out there.
