### ISSUE TITLE
space usage statistics

### ISSUE THREAD

**Issue by lnussel** [openSUSE/snapper#418]
There are some tools that claim to display how much data is shared between snapshots etc:
https://github.com/GrahamCobb/extents-lists

Maybe something like that could be integrated into snapper as well?

**Comment by roosemberth** [comment]
I usually use this command and compare side by side the exclusive usage of each snapshot:
```
for f in $(mount | grep btrfs | grep device | awk '{print $3}'); do
    sudo btrfs subvolume show $f 2>/dev/null | tail -n+14
done | awk '{print $1}' | xargs -I ici sudo btrfs filesystem du -s /mnt/root-btrfs-device/ici | grep -v "Total   Exclusive  Set shared  Filename"
```
Where `/mnt/root-btrfs-device` is the mounting point that contains the root subvol of `device` (ie. all other subvolumes are located bellow that path).

Sidenote: this command takes time and there's probably a more efficient way to do it programatically.

**Comment by aschnell** [comment]
By now snapper can display the exclusive space used by snapshots.
