### ISSUE TITLE
pam_snapper allow config without prefix

### ISSUE THREAD

**Issue by Magissia** [openSUSE/snapper#422]
On mono users machines, it makes sense to have one "home" config and not have a per user snapper config if users are not supposed to be able to recover themselves. (snapshots are backed up to another remote machine and deleted from local machine)

**Comment by aschnell** [comment]
So the goal is to snapshot /home whenever any user logs on or off? Doesn't that result in a strange accumulation of snapshots where the timeline would make more sense?
