### ISSUE TITLE
Don't hardcode snapshots directory

### ISSUE THREAD

**Issue by wesbarnett** [openSUSE/snapper#423]
Currently every configuration hardcodes the snapshots directory to be `.snapshots`. It would be nice if this could be changed in the configuration. For example, let's say I could have two configurations for `/`. One of those has `/.snapshots` as its snapshots directory. The other could have `/mnt/backup/snapshots` as its directory. I could then mount a usb drive and take a snapshot with that configuration.

**Comment by aschnell** [comment]
Snapshots must be on the same file system. So if / and /mnt/backup/snapshots are different btrfs file systems it does not work (already btrfs limitation).
