### ISSUE TITLE
Snapper create config for xfs filesystem not working

### ISSUE THREAD

**Issue by benyraja** [openSUSE/snapper#426]
I tried to create a config for lvm xfs, but it failed with below message

$ snapper -c temp create-config --fstype="lvm(xfs)" /var/tmp
Creating config failed (invalid filesystem type).

$ snapper --version
snapper 0.5.6
flags btrfs,lvm,no-ext4,xattrs,no-rollback,no-btrfs-quota,no-selinux

I'm using Rhel 7.4 version.

My LVM configuration for /var/tmp
 --- Logical volume ---
  LV Path                /dev/vglocal/tmp
  LV Name                tmp
  VG Name                vglocal
  LV UUID                zIPlv1-kcbC-Ysrn-Tb1h-ESTn-QYAh-jaHA92
  LV Write Access        read/write
  LV Creation host, time eilabdellvm07, 2016-08-01 14:24:16 -0400
  LV Status              available
   open                 1
  LV Size                2.00 GiB
  Current LE             512
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     8192
  Block device           253:3

Can anyone help me to fix this?

Thanks,
Beny

**Comment by aschnell** [comment]
Please provide /var/log/snapper.log and the output of "lvs" and "mount".

**Comment by aschnell** [comment]
No response.
