### ISSUE TITLE
Create a snapshot of an existing snapshot (not current state)

### ISSUE THREAD

**Issue by rainbowtux** [openSUSE/snapper#428]
I am writing some scripts to have atomic updates and I am basing my work on btrfs + snapper. As far as I can find, snapper currently only allows to take a snapshot of the current state and not of an existing snapshot, which is what I need.

People can login to the system and change the current state for debugging purposes etc, but I want to prevent those changes from persisting by
- adding a snapper rollback to the last official update snapshot for every reboot
- start my update with a snapshot of the last official update snapshot

Taking the current state for the snapshot could have side effects when support has altered the system state manually.

In the code, most of what is needed already seems to be there, but not exposed to the user via the snapper command.

Can this be added as a feature?

**Comment by aschnell** [comment]
AFAIS https://github.com/openSUSE/snapper/pull/497 implements this.
