### ISSUE TITLE
OBS: key expired in Ubuntu 16.04

### ISSUE THREAD

**Issue by itanaxima** [openSUSE/snapper#434]
pub   2048R/324E6311 2014-05-12 [expired: **2018-09-27**]
uid                  filesystems OBS Project <filesystems@build.opensuse.org>

**Comment by aschnell** [comment]
As far as I know the key is updated when the package builds.

In any case the Ubuntu 16.04 repository has been removed from the snapper project since it does not build anymore due to some outdated libraries.
