### ISSUE TITLE
Spawn snapperd using systemd (on a systemd machine)

### ISSUE THREAD

**Issue by SunilMohanAdapa** [openSUSE/snapper#441]
Currently, when we run `snapper` commands `snapperd` is automatically launched using dbus activation mechanism. On a system running systemd, there are benefits doing launching using systemd. For example, one can set extra security options like restricting capabilities, syscalls, temporary directories, mount points, files. It is also easy to find the manage the running daemon.

My use case was that I took a backup of snapperd configurations and restored them later. After a restore, snapperd does not see the new configuration (from the restored configuration files). Typically, for other daemons, we would restart or reload the daemon. However, this is not simple with `snapperd`. In my backup program, I ended up querying the DBus daemon for PID of snapperd and killed it (expecting it to auto-spawn again when needed). It would have been nice to ask systemd to simply restart the daemon.

If I understand correctly, this can be done by writing a systemd service file snapperd with `BusName=` and then by adding `SystemdService=` in the DBus service file. This should not cause issues on systems that don't run systemd.

**Comment by aschnell** [comment]
I assume https://github.com/openSUSE/snapper/pull/551 implements this.
