### ISSUE TITLE
issues with building snapper with boost1.68

### ISSUE THREAD

**Issue by sww1235** [openSUSE/snapper#459]
Hello: 

I am attempting to update void linux's package of snapper to 0.8.1 ( https://github.com/void-linux/void-packages/pull/5330 ) but am running into issues since we are on boost1.68. 

I am not experience enough to tell if the errors I am seeing in travis are snapper related or somehow boost related.

I would be glad to assist in any way, but got in over my head once things weren't building.

**Comment by aschnell** [comment]
See https://github.com/void-linux/void-packages/pull/5330.

**Comment by spencerjanssen** [comment]
NixOS has the same build failure since updating to btrfs-progs 4.19.  I tracked the issue down to kdave/btrfs-progs@c6039704c.  The `swap` macro defined in `kerncompat.h` is conflicting with Boost's use of `swap`.

**Comment by sww1235** [comment]
@spencerjanssen thanks for finding that. I think your patch should fix it since we just need to get rid of the btrfs swap in this instance.

**Comment by aschnell** [comment]
Should be "fixed/workarounded" by https://github.com/openSUSE/snapper/pull/460.
