### ISSUE TITLE
Build failure with Boost 1.63.0

### ISSUE THREAD

**Issue by GreatEmerald** [openSUSE/snapper#467]
When building Snapper 0.5.6 against Boost 1.63.0, users are reporting build failures like this:

```
                 from /usr/include/boost/thread.hpp:13,
                 from Btrfs.cc:45:
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_pair.h:419:21: error: macro "swap" requires 2 arguments, but only 1 given
       swap(pair& __p)
                     ^
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_pair.h:490:50: error: macro "swap" passed 4 arguments, but takes just 2
```

See also: https://bugs.gentoo.org/670952

**Comment by aschnell** [comment]
It is caused by btrfs header files defining a swap macro and meanwhile fixed (in snapper and btrfs-progs), see https://github.com/openSUSE/snapper/issues/459 and links therein.
