### ISSUE TITLE
Critical: After upgrade to Ubuntu 19 automatic snapshot freezes computer during any apt-get install

### ISSUE THREAD

**Issue by jbrepogmailcom** [openSUSE/snapper#481]
I need to know how to manually disable automatick snapshots created during "apt-get install". After upgrade to Ubuntu 19.04, whenever I want to install or remove anything whole computer freezes when creating the snapshot. So I can not uninstall / reinstall snapper, because it involves automatic snapshots too. I need first to manually disable automatic snapshots and then remove and reinstall snapper.

**Comment by aschnell** [comment]
I suggest to ask this question in an Ubuntu forum.

**Comment by R1dO** [comment]
The default snapper package under ubuntu 19.04 places the file `80snapper` under `/etc/apt/apt.conf.d/`.
You can try to **temporarily** disable both lines in there (e.g. start the lines with a `#`) to see if that fixes your problem.

**Comment by aschnell** [comment]
Looks like a Ubuntu specific problem.
