### ISSUE TITLE
It took too long to restore the snapshot

### ISSUE THREAD

**Issue by tom-TangT** [openSUSE/snapper#490]
I am a developer and have errors when using snapper to create snapshots and delete snapshots
![image](https://user-images.githubusercontent.com/52006536/62853760-da8fbe00-bd1f-11e9-902a-5c5324c4c10e.png)
I found that restoring snapshots took longer, typically 30ms. Is it possible to reduce it below 2ms? By the way, I'm using a normal snapshot, and when using pre/post snapshots, the recovery time can be reduced to less than 10ms
At the same time,There was a 'dbus' error when using snapper. Instead, add '--no-bus' to each snapper to avoid the error.It is not known if this is the reason why it takes longer to restore the snapshot.
Help!

**Comment by tom-TangT** [comment]
![image](https://user-images.githubusercontent.com/52006536/62854350-acab7900-bd21-11e9-8ba6-cdb930111bc7.png)

**Comment by tom-TangT** [comment]
![image](https://user-images.githubusercontent.com/52006536/62854391-cb117480-bd21-11e9-911e-8d7087968ed9.png)

**Comment by tom-TangT** [comment]
anyone konws?

**Comment by aschnell** [comment]
Looks as if nobody known what to say here.

From my point of view assuming anything in the ms range with filesystems is not possible. Even in general for such small times a real time operation system is required.

In any case snapper does not make guarantees about timing.
