### ISSUE TITLE
Snapper stopped working after updating btrfs-progs

### ISSUE THREAD

**Issue by jezekra1** [openSUSE/snapper#500]
After updating btrfs-progs to 5.3-1 on arch, snapper is not working and displays this message:
```$ sudo snapper list```
```snapper: symbol lookup error: /usr/lib/libbtrfs.so.0: undefined symbol: write_raid56_with_parity```

**Comment by aschnell** [comment]
Likely a problem like issue #473.

**Comment by aschnell** [comment]
I contacted btrfs developers and Johannes Thumshirn posted a fix on the linux-btrfs mailing list within minutes.

**Comment by julien-noblet** [comment]
There is also a pull request on btrfs-progs depot: https://github.com/kdave/btrfs-progs/pull/215

**Comment by jezekra1** [comment]
Solved in `btrfs-progs` 5.3.1-1
