### ISSUE TITLE
SPACE_LIMIT and FREE_LIMIT should support actual sizes

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/snapper#507]
By default, users have:

```ini
# fraction of the filesystems space the snapshots may use
SPACE_LIMIT="0.5"

# fraction of the filesystems space that should be free
FREE_LIMIT="0.2"
```

In Tumbleweed, default installation is a single Btrfs file system and `/home` or `/var` will be excluded from snapshots. If you have 1TB hard drive, this means 500GB will be used for snapshots, which is too much for most users.

For desktop/workstation users, default configuration like this is more convenient (the value can be different for best safety and stability consideration, can be different on desktop, server, container etc.):

```ini
# filesystems space the snapshots may use, can be:
# fraction: 0.5, 0.25
# size: 15g, 2500m
SPACE_LIMIT="20g"

# filesystems space that should be free, can be:
# fraction: 0.5, 0.25
# size: 15g, 2500m
FREE_LIMIT="10g"
```

**Comment by aschnell** [comment]
Absolute values are now supported by https://github.com/openSUSE/snapper/pull/633. The defaults have not changed.
