### ISSUE TITLE
documentation of configuration options

### ISSUE THREAD

**Issue by matchuek** [openSUSE/snapper#508]
The man-page snapper-configs(5) does not explain the possible values of e. g. the SPACELIMIT option:
```
SPACE_LIMIT=float
           Limit for the fraction of the filesystems space the snapshots should use.
```
It should give more information like
```
Accepted Values:
    fraction: 0.5, 0.25
    size: 15g, 2500m
```

**Comment by aschnell** [comment]
Absolute sizes are not possible for that parameter. The default value is mentioned so the format of the fraction should also be clear.
