### ISSUE TITLE
support for "thick" LVM snapshots?

### ISSUE THREAD

**Issue by anarcat** [openSUSE/snapper#511]
Why does snapper only support "thin" LVM snapshots? I have been a heavy user of LVM and never used those kind of snapshots, partly because they require setting up the LV differently from the start but, I must admit, mostly because I didn't know about them.

Changing LV types makes me queasy. I am not sure I like the "ethereal" nature of "thin" LVM snapshots: I do like to know how much space I have allocated and where, and make that a solid commitment. This requires me to use normal LVM snapshots, which I'll call "thick" for the purpose of this conversation.

Why can't snapper use "thick" LVM snapshots? *Does* it work with normal snapshots at all? Is there any "thin" functionality it requires for operation? Are you fundamentally opposed to "thick" snapshots?

Thanks!

**Comment by aschnell** [comment]
One big disadvantage of thick snapshots is the performance penalty: When 10 thick snapshots have been made and the original data is modified, the difference is written to all 10 snapshots. Having 10 or more snapshots is common with snapper. So snapper with thick snapshots would become terrible slow.

BTW: "thick" is the general term for non thin snapshots.

**Comment by anarcat** [comment]
thanks for the response, i suspected as much... i guess i should start experimenting with thin snapshots as well. i wonder why the debian installer doesn't use them by default...
