### ISSUE TITLE
Website snapper.io slow due to piwik.js timeout

### ISSUE THREAD

**Issue by KoviRobi** [openSUSE/snapper#513]
Hi,

The website snapper.io is slow, due to waiting on a timeout of `piwik.js`. I have tried it on my phone network, as well as the very reliable university network, so possibly it's not on my end. I do have the following output on the Chromium browser console, which seems relevant. By blocking the `piwik.js` the website behaves normally.

![2019-12-17-153211_1279x263_scrot](https://user-images.githubusercontent.com/1903418/71020729-cd7f4300-20f4-11ea-82fb-2406215f1843.jpg)

**Comment by aschnell** [comment]
Works fine for me.

**Comment by KoviRobi** [comment]
Hmm, I'll have to try some random internet coffee shop, but presumably the following works for you:
```
$ curl http://beans.opensuse.org/piwik/piwik.js                                                                          
curl: (7) Failed to connect to beans.opensuse.org port 80: Connection timed out                                                                               
```
At least I know it's not just Chromium

**Comment by aschnell** [comment]
Ah, that curl command does indeed not work for me. AFAICS my firefox is blocking social media trackers and stuff like that.

**Comment by aschnell** [comment]
I have disabled the code now for the time being.
