### ISSUE TITLE
Snapper unable to tell which snapshot is currently active  

### ISSUE THREAD

**Issue by evertonstz** [openSUSE/snapper#515]
Usually on SUSE I'm able to see the active snapshot just by running `snapper list`, I'm currently on Manjaro and I'm able to use snapper normally and when I run list I can see every snapshot, the problem is that snapper can't seem to recognize the current snapshot (therefore there's no * before the snapshot's number). Ofc I went and tried `snapper list --columns active` and every snapshot is listed as "no".

**Comment by aschnell** [comment]
The active snapshot may not be a snapshot snapper knows about (and lists).

The output of 'btrfs subvolume list /' and 'btrfs subvolume get-default /' together with /proc/mounts should help to see what is going on.

**Comment by evertonstz** [comment]
Tbh I'm not sure what I'm supposed to with all those commands and what to do with them to fix the problem, I know what snapshot I'm currently on because I use [snap-pac](https://github.com/wesbarnett/snap-pac) to create pre-pos snapshots, so I'm probably in the last "pos" I guess?

Here are the outputs:
[snapper list](https://pastebin.com/raw/xijD2zPj)
[btrfs subvolume list /](https://pastebin.com/raw/UXSkAT43)
[btrfs subvolume get-default /](https://pastebin.com/raw/Phi47wJt)
