### ISSUE TITLE
snapper create --command only snapshots changes on a single subvol.

### ISSUE THREAD

**Issue by johndickinson** [openSUSE/snapper#529]
For example if the command was (/ and /opt are different subvols) 
```
#!/usr/bin/env bash
touch /test
touch /opt//test
```

and you ran it like `sudo snapper create --command ./test.sh --print-number --cleanup-algorithm=number --description="test"`

then you can see the pre and post only in the /.snapshot recording the first touch and nothing in /opt/.snapshot recording the second touch

I have no idea how you could fix this but it would be a nice thing to have.

**Comment by aschnell** [comment]
With btrfs snapshots stop a subvolumes. So you have to create a snapper config for the /opt subvolume and the tell snapper to create snapshots of both / and /opt (using two snapper calls).
