### ISSUE TITLE
cannot access template config

### ISSUE THREAD

**Issue by Dulanic** [openSUSE/snapper#534]
I am attempted to create a snapshot config /w 

`snapper -c root create-config -f btrfs /`

This results in the following error:

`Creating config failed (cannot access template config).`

I have removed and reinstalled all snapper to try to see if it was a install problem /w sudo apt-get purge snapper and then sudo apt-get autoremove and reinstalled. No change.

I was following the guide from https://wiki.archlinux.org/index.php/Snapper#Create_a_new_configuration

I am using ubuntu 19.10 and added the repo from snapper.io

**Comment by aschnell** [comment]
I suppose the file /etc/snapper/config-templates/default is missing. It should be included in one of the packages.

**Comment by Dulanic** [comment]
Yeah, I get that, I just have purged and reinstalled multiple times via the repo as defined on the main page.

https://software.opensuse.org/download/package?project=filesystems:snapper&package=snapper

```
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/filesystems:/snapper/xUbuntu_19.10/ /' > /etc/apt/sources.list.d/filesystems:snapper.list"
wget -nv https://download.opensuse.org/repositories/filesystems:snapper/xUbuntu_19.10/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update
sudo apt-get install snapper
```

**Comment by aschnell** [comment]
The templates should be in the libsnapper package.

**Comment by Dulanic** [comment]
```Reading package lists... Done
Building dependency tree
Reading state information... Done
libsnapper is already the newest version (0.8.9).
libsnapper set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.```

**Comment by aschnell** [comment]
But the libsnapper package includes the template:

# dpkg -c libsnapper_0.8.9_i386.deb
[...]
-rw-r--r-- root/root      1169 2020-01-16 14:03 ./etc/snapper/config-templates/default
[...]

Since I have not much experience with Debian I cannot gibe further help.

**Comment by Dulanic** [comment]
got it, closing 20th purge & reinstall was the charm
