### ISSUE TITLE
Failure (org.freedesktop.DBus.Error.ServiceUnknown)

### ISSUE THREAD

**Issue by sakurarain99** [openSUSE/snapper#537]
The system is archlinux, at least the kernel, u disk mounts the disk partition, uses arch-chroot to enter the system, and all commands that use snapper fail (org.freedesktop.DBus.Error.ServiceUnknown), please ask what is the reason

**Comment by mcepl** [comment]
System is openSUSE/Tumbleweed (as of today, 2020-08-30, snapper 0.8.12-1.2) and this is what I get with the default installation:
```
stitny:~# systemctl status snapper-cleanup
● snapper-cleanup.service - Daily Cleanup of Snapper Snapshots
     Loaded: loaded (/usr/lib/systemd/system/snapper-cleanup.service; static; vendor preset: disabled)
     Active: failed (Result: exit-code) since Sun 2020-08-30 19:37:45 CEST; 1h 29min ago
TriggeredBy: ● snapper-cleanup.timer
       Docs: man:snapper(8)
             man:snapper-configs(5)
   Main PID: 17777 (code=exited, status=1/FAILURE)

Aug 30 19:37:45 stitny systemd[1]: Started Daily Cleanup of Snapper Snapshots.
Aug 30 19:37:45 stitny systemd-helper[17777]: Selhání (org.freedesktop.DBus.Error.Spawn.ExecFailed).
Aug 30 19:37:45 stitny systemd[1]: snapper-cleanup.service: Main process exited, code=exited, status=1/FAILURE
Aug 30 19:37:45 stitny systemd[1]: snapper-cleanup.service: Failed with result 'exit-code'.
stitny:~#
```

**Comment by mcepl** [comment]
The same for ``snapper-timeline``:
```
stitny:configs# systemctl status snapper-timeline
● snapper-timeline.service - Timeline of Snapper Snapshots
     Loaded: loaded (/usr/lib/systemd/system/snapper-timeline.service; static; vendor preset: disabled)
     Active: failed (Result: exit-code) since Sun 2020-08-30 21:00:15 CEST; 12min ago
TriggeredBy: ● snapper-timeline.timer
       Docs: man:snapper(8)
             man:snapper-configs(5)
   Main PID: 22255 (code=exited, status=1/FAILURE)

Aug 30 21:00:15 stitny systemd[1]: Started Timeline of Snapper Snapshots.
Aug 30 21:00:15 stitny systemd-helper[22255]: Selhání (org.freedesktop.DBus.Error.Spawn.ExecFailed).
Aug 30 21:00:15 stitny systemd[1]: snapper-timeline.service: Main process exited, code=exited, status=1/FAILURE
Aug 30 21:00:15 stitny systemd[1]: snapper-timeline.service: Failed with result 'exit-code'.
stitny:configs# 
```

**Comment by aschnell** [comment]
Maybe https://github.com/openSUSE/snapper/pull/551 is the solution. But there error message I get in that case is "Failure (org.freedesktop.DBus.Error.Spawn.PermissionsInvalid)".

**Comment by matty-r** [comment]
I'm also getting this error when attempting to set it up during Arch Linux installation via arch-chroot.

**Comment by aschnell** [comment]
To debug another problem I installed Arch Linux a few days ago and did not have any problems (except of the one I wanted to reproduce and fixed meanwhile). So unfortunately someone who actually has this problem must debug it.

And concerning use of arch-chroot: I'm not sure dbus is available in the chrooted system.

**Comment by loynoir** [comment]
> To debug another problem I installed Arch Linux a few days ago and did not have any problems (except of the one I wanted to reproduce and fixed meanwhile). So unfortunately someone who actually has this problem must debug it.
> 
> And concerning use of arch-chroot: I'm not sure dbus is available in the chrooted system.

@aschnell According to my past experience
1. `chroot` environment is a environment without `dbus` and `systemd` related stuff.
2. `systemd-nspawn` environment is a chroot-alike enviroment with `dbus` and `systemd` related stuff.
3. If you do not have chroot-able or systemd-nspawn-able environment, may be you can try add `systemd.unit=emergency.target` to grub.cfg stuff, 
I remember snapper not work at that environment too.

Personaly, I'm a new snapper user. 
May I ask, is snapper supposed to support environment without dbus?
If so, it will be great!

Few minutes ago, I just roll back my archlinux from failure of upgraded gdm. And I found snapper rollback not work at that chroot environment, so I have to rollback manully.

**Comment by aschnell** [comment]
snapper has the ```--no-dbus``` option for such environments.

**Comment by loynoir** [comment]
Oh, that is nice! Thanks a lot for your reply.

**Comment by Freed-Wu** [comment]
Why not make `--no-dbus` be added by default when it will met this error? It can make user's experience better.

**Comment by Sitolam** [comment]
> Why not make `--no-dbus` be added by default when it will met this error? It can make user's experience better.

+1
I had to come to this issue to fix the issue but it could just be automatic.
