### ISSUE TITLE
snapper does not work after upgrade to 0.8.13 on OMV5 with Debian10 

### ISSUE THREAD

**Issue by bahrthaare** [openSUSE/snapper#557]
I upgraded snapper on my OMV5 NAS with Debian10 to the version 0.8.13. After the upgrade snapper doesn't work correctly.
If I want to list my snapper configs or want to do a snappshot I geht this from `journalctl --all -f`

`dbus-daemon[643]: [system] Activating via systemd: service name='org.opensuse.Snapper' unit='snapperd.service' requested by ':1.1102' (uid=0 pid=26445 comm="snapper list-configs ")`
`dbus-daemon[643]: [system] Activation via systemd failed for unit 'snapperd.service': Unit snapperd.service not found.`

I don't think that snapper was running as systemd service before the upgrade.

**Comment by bahrthaare** [comment]
I installed snapper with the commands

`echo 'deb http://download.opensuse.org/repositories/filesystems:/snapper/Debian_10/ /' | sudo tee /etc/apt/sources.list.d/filesystems:snapper.list
curl -fsSL https://download.opensuse.org/repositories/filesystems:snapper/Debian_10/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/filesystems:snapper.gpg > /dev/null
sudo apt update
sudo apt install snapper`

and I was able to upgrad to Version 0.8.13.
I removed snapper 0.8.13 completely and the source.list entry an reinstalled 0.8.2-1.
Now snapper uses systemd and not cron as it does before the upgrade to 0.8.13 but im Ok with using systemd and snapper is now working correctly again without errors.
I'm thinking 0.8.13 is not for use with Debian 10 but I don't now why it let me upgrade to that version.

**Comment by aschnell** [comment]
That is likely because the new file /usr/lib/systemd/system/snapperd.service is missing. It was added to the spec file for SUSE/Fedora but not the Debian file.

You could try to install it manually. It is available at https://github.com/openSUSE/snapper/blob/master/data/snapperd.service.

**Comment by bahrthaare** [comment]
> You could try to install it manually. It is available at https://github.com/openSUSE/snapper/blob/master/data/snapperd.service.
> 
> See #551.

Yes, that seems to work.
