### ISSUE TITLE
Timeline cleanup doesn't work as expected.

### ISSUE THREAD

**Issue by darkdragon-001** [openSUSE/snapper#568]
In addition to #373, I face another issue:

Timeline is configured to keep the last 48 hourly snapshots. I turn my laptop off at night, so only about 10 snapshots are created per day.

*Expected behavior*

Only keep hourly snapshots for the last 48 hours (in my case ~20).

*Current behavior*

Keep the last 48 snapshots independently of the time when they were taken.

**Comment by aschnell** [comment]
No, the timeline works as expected (as documented).

And the behaviour also seems better to me: Suppose the timeline would keep the hourly snapshots of the last 10 hours. Now the system is turned on after two days and as a result *all* hourly snapshots are removed. That renders the timeline useless.

**Comment by darkdragon-001** [comment]
Well, in your described case, the other rules would come into context: daily, weekly, monthly, yearly -> they would keep the fraction according to their rule. If one wants to keep the last N snapshots (the behavior you described), there are also NUMBER snapshots and rules.

This behavior is btw what I am used to from other backup programs like restic:
https://restic.readthedocs.io/en/latest/060_forget.html#removing-snapshots-according-to-a-policy

**Comment by darkdragon-001** [comment]
@aschnell Can you point me to some documents where the behavior was discussed? Furthermore, what is the difference between _number snapshots_ and _daily timeline snapshots_ with the current behavior?

**Comment by infinity0** [comment]
I reopened this issue as #885 with a more explicit title, more detailed argumentation, and concrete examples.
