### ISSUE TITLE
snapshots subvolume should better be flat than nested to a parent which could be rolled back

### ISSUE THREAD

**Issue by darkbasic** [openSUSE/snapper#577]
My issue with nested subvolumes is that their parent subvolume must be kept around in order to preserve them, while I would gladly delete my old default btrfs subvolume after a rollback in order to save space.
What I like to do is to create a `snapshots` flat subvolume and create nested subvolumes for each config from there (snapshots/root, snapshots/home, etc). They're still technically nested, but they're basically flat because I'm never going to rollback their parent `snapshots` subvolume.

**Comment by aschnell** [comment]
I'm not so sure that I understand the problem correctly.

On SUSE the system is already installed into a subvolume (other than the top level) so it is possible to delete that subvolume after a rollback to save space.

In general snapper implements the snapshot setup of SUSE - not the other way around. So such things are better discussed on a SUSE mailing list, e.g. opensuse-factory.

**Comment by darkbasic** [comment]
@aschnell let me try to explain it with an example.

If you run `snapper -c home create-config /home` it will create the `/home/.snapshots` subvolume.
If you mess up and decide to rollback home, then the existing `/home` subvolume (which contains `.snapshots`) will be left unused and a new subvolume (which **doesn't** contain `.snapshots`) gets used instead.
If you want to regain space you will have to delete the old `/home` volume which you previously messed up, but in order to do so you will have to also delete its `.snapshots` subvolume (which is still currently used).
