### ISSUE TITLE
[Question] Rolling back subvolumes other than root

### ISSUE THREAD

**Issue by darkbasic** [openSUSE/snapper#578]
I admit I'm not in love with the whole idea of discarding existing subvolumes each time you roll back a snapshot, but admittedly it works well for the root thanks to the btrfs default subvolume (you simply make use of it in fstab/grub). But what about subvolumes other than root, for example home? How are you supposed to know which one is the currently active one?

**Comment by aschnell** [comment]
No snapshots are discarded when doing a rollback.

Rollback the way it is done in SUSE right now only works for the root. If you want to rollback other subvolumes you can manually edit fstab and add the subvol option. The big disadvantage is that rollbacks for root might also effect other rollbacks then.

**Comment by darkbasic** [comment]
> No snapshots are discarded when doing a rollback

With "discarded" I meant that the existing subvolume is left unused instead of being substituted with a rw copy of the subvolume you want to roll back to.

> Rollback the way it is done in SUSE right now only works for the root

Oh, that's unfortunate.

@aschnell Why don't you simply move a rw copy of the target subvolume in place of the existing snapshot? That would remove all of the issues with non-root volumes and allow to rollback without fiddling with fstab or tricks like default subvolumes.
