### ISSUE TITLE
Link FAQ: dead link (404)

### ISSUE THREAD

**Issue by ratijas** [openSUSE/snapper#584]
This link on the [FAQ page](http://snapper.io/faq.html) is dead:

https://github.com/openSUSE/snapper/blob/14fecb6dad443aee17effca43d557a1326bd7594/faq.html#L93

![Screenshot_20201012_212217](https://user-images.githubusercontent.com/6737986/95778547-036b6480-0cd1-11eb-8144-ee1364a62670.png)

**Comment by aschnell** [comment]
Fixed by https://github.com/openSUSE/snapper/commit/5d13411705fda623be1ef1c6e4969e2cb1e0b945.
