### ISSUE TITLE
Snapper not working on Alpine

### ISSUE THREAD

**Issue by xfbs** [openSUSE/snapper#587]
Hey guys, awesome piece of kit, I've been using snapper on Ubuntu and it works like a charm.
However I wanted to use it on an Alpine machine as well, it's in the edge testing repository, version 0.8.14, so I gave installing that a shot.
Problem is, nothing seems to work. I can't create a config:
```
horatius:~# snapper -c root create-config /
Failed to set locale. Fix your system.
Failure (org.freedesktop.DBus.Error.NoReply).
```
I looked in the open bugs and tried to fix the dbus message size limit thing to see if that did anything, but no dice.
```
horatius:~# cat /etc/dbus-1/system.d/message.conf
<!DOCTYPE busconfig PUBLIC
 "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
        <limit name="max_incoming_bytes">100000000</limit>
        <limit name="max_outgoing_bytes">100000000</limit>
        <limit name="max_message_size">100000000</limit>
</busconfig>
```
I also tried using it without dbus, and no luck either.
```
horatius:~# snapper -c root --no-dbus create-config /
Failed to set locale. Fix your system.
Listing configs failed (sysconfig-file not found).
```
I don't really know what a sysconfig file is supposed to be. Could someone help me out?

**Comment by aschnell** [comment]
The sysconfig file is /etc/sysconfig/snapper. It has to exist.
