### ISSUE TITLE
Can I use snapper on Centos 7 with NAS NFS mounted directory?

### ISSUE THREAD

**Issue by naderskf** [openSUSE/snapper#600]
Hello,

I have an NFS home directory which is located in a Synology NAS device, I want to take snapshots of /home periodically using snapper. On NAS I have /home configured as btrfs, but it is mounted on Centos 7 as NFS. When I try to create a config file on /home I get this message:

[root@glenmorangie]# snapper -c my_temp_snaps create-config /home
Creating config failed (invalid filesystem type).

Any help is appreciated.

**Comment by aschnell** [comment]
Unfortunately snapper cannot be used if the btrfs is on a remote server.
