### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by claell** [openSUSE/snapper#614]
Trying to get started with snapper, I found some not unclear on contradictory points mainly concerning the automatic creation of snapshots and their (automatic) deletion.

On http://snapper.io/manpages/snapper.html it says:
```
Next to manual snapshot creation, snapshots are also created automatically.

    A cron-job creates hourly snapshots.
```

This is afaict misleading as on http://snapper.io/manpages/snapper-configs.html it says:
```
 TIMELINE_CREATE=boolean

    Defines whether hourly snapshots should be created.

    Together with the timeline cleanup algorithm this will create a collection of snapshots with more snapshots is the near past and less snapshots in the far past.

    Default value is "no".
```

So to my understanding there are no automatic snapshots taken by default.

Similarly, in the cleanup algorithm section of the overall manpage, it is not stated that those are not enabled by default.

Lastly, I don't entirely understood the logic behind the cleanup algorithms (are all snapshots including manual ones considered or just the cron based hourly ones from TIMELINE_CREATE? Also if I read it correctly those hourly ones can also be treated as daily, weekly etc. snapshot when it comes to evaluate deletion?).

**Comment by claell** [comment]
Hm, after creating a config now, I see that some values that are `no` by default are explicitly set there to be `yes`, probably derived from `/etc/snapper/config-templates`?

The comments in that file seem to say that `TIMELINE_CLEANUP` will only delete automatically created snapshots:
```
# cleanup hourly snapshots after some time
TIMELINE_CLEANUP="yes"
```

Not sure about `NUMBER_CLEANUP`, though.

**Comment by claell** [comment]
I read now that one has to specify a cleanup algorithm when taking a manual snapshot, so by default manual snapshots don't seem to get deleted automatically.

**Comment by aschnell** [comment]
The default values are indeed a bit confusing. When creating a new config the values from /etc/snapper/config-templates/default are used (unless the user specifies a different file). There TIMELINE_CREATE="yes". So normally the timeline is enabled.

The default values mentioned in snapper-configs are the values snapper uses when the value is not present. That is mentioned in the documentation.

And finally on SUSE the value for TIMELINE_CREATE is changed by YaST to "no" during installation.

To know the value used, check the output of 'snapper get-config'. For missing values there, check snapper-configs.

**Comment by claell** [comment]
Thanks for the clarification. Is there a reason for the discrepancies (at least the ones between the default template and the default value for this property)?

Still I hope that the documentation can be improved on this to avoid confusion.

**Comment by aschnell** [comment]
The discrepancies are due to compatibility: When feature XYZ is added it might not be desired to turn it on for existing systems, so by default in snapper it must be off. On the other hand for new systems it might be desired to turn it on so in the default template it can be on.

**Comment by claell** [comment]
Mh, but I assume the default template is the same no matter what system is used? That would mean that for the user there is not really a difference which way the feature is enabled by default.

Regardless, I still hope that this can be clarified slightly in documentation.
