### ISSUE TITLE
OBS: key expired in Ubuntu 20.04

### ISSUE THREAD

**Issue by AnLAdmin** [openSUSE/snapper#619]
Ubuntu 20.04
Snapper 0.8.14

# apt-key list
pub   rsa2048 2018-10-19 [SC] [expired: 2020-12-27]
      2A65 8CFA 6380 FA92 EAE4  A854 248B F908 2524 EEFD
uid           [ expired] filesystems:snapper OBS Project <filesystems:snapper@build.opensuse.org>

Looks like issue #265.
Can't update. Would appreciate help.

**Comment by aschnell** [comment]
For once snapper has been at version 0.8.15 several weeks already.

And as far a I can tell key ("Release.key") at https://download.opensuse.org/repositories/filesystems:/snapper/xUbuntu_20.04/ is still valid:

pub   rsa2048 2018-10-19 [SC] [expires: 2023-02-22]
      2A658CFA6380FA92EAE4A854248BF9082524EEFD
uid           filesystems:snapper OBS Project <filesystems:snapper@build.opensuse.org>

Maybe the key was renewed meanwhile (timestamp is 2021-01-08).

**Comment by AnLAdmin** [comment]
Well, **apt update** also gives me this errors:
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/filesystems:/snapper/xUbuntu_20.04  InRelease: The following signatures were invalid: EXPKEYSIG 248BF9082524EEFD filesystems:snapper OBS Project <filesystems:snapper@build.opensuse.org>
W: Failed to fetch http://download.opensuse.org/repositories/filesystems:/snapper/xUbuntu_20.04/InRelease  The following signatures were invalid: EXPKEYSIG 248BF9082524EEFD filesystems:snapper OBS Project <filesystems:snapper@build.opensuse.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by adrianschroeter** [comment]
that project may need to extend the signing key and republish.

see 

# osc signkey --extend

**Comment by aschnell** [comment]
OK, I have executed the command to extend the key. A new package should trigger republishing.

**Comment by aschnell** [comment]
Another user told me that apt does not refresh keys automatically. I found https://serverfault.com/questions/7145/what-should-i-do-when-i-got-the-keyexpired-error-message-after-an-apt-get-update which explains how to do it manually.

**Comment by AnLAdmin** [comment]
Well it worked after I updated the key with:
$ sudo apt-key adv --keyserver keys.gnupg.net --recv-keys <EXPKEYSIG>
