### ISSUE TITLE
Use ConditionPathExists for boot.service systemd service

### ISSUE THREAD

**Issue by ftsell** [openSUSE/snapper#630]
# The problem
In my setup I only use snapper to take periodic snapshots of my data partition and therefore only have a config named 'data'. When booting the system, I see that the unit `snapper-boot.service` fails with the log entry `The config 'root' does not exist. Likely snapper is not configured.`. Now since I also have monitoring of failed systemd units set up and my distro enables this unit per default this was an annoying surprise.

# Proposed solution
Systemd supports the directive [`ConditionPathExists=`](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#ConditionPathExists=) in its unit files for units that should only be executed under certain conditions and otherwise be skipped. This condition could be added to [data/boot.service](https://github.com/openSUSE/snapper/blob/master/data/boot.service) like 
```
[Unit]
ConditionPathExists=/etc/snapper/configs/root
```

**Comment by aschnell** [comment]
Implemented with https://github.com/openSUSE/snapper/pull/635.
