### ISSUE TITLE
symbol lookup error: snapper: undefined symbol: _ZNK7snapper4UuidltERKS0_

### ISSUE THREAD

**Issue by nemonein** [openSUSE/snapper#637]
Hello.
I installed snapper version 0.8.16-1 on Ubuntu 20.04 server, from the [opensuse repository](http://download.opensuse.org/repositories/filesystems:/snapper/xUbuntu_20.04/).

Then, I've got this error.
```
$ snapper --version
snapper: symbol lookup error: snapper: undefined symbol: _ZNK7snapper4UuidltERKS0_
```

I thought this might be related to `btrfs-progs`, so I've installed the latest version of it, which was 5.10.1.
However, the error persists.

Any help would be appreciated.

**Comment by aschnell** [comment]
The missing symbol is likely the new operator< for Uuid introduced by https://github.com/openSUSE/snapper/pull/633.

Did you also install libsnapper from that repository? Since the minor number of the library was increased the package manager should enforce that but maybe that does not work.

**Comment by nemonein** [comment]
Thank you for your reply.
`libsnapper` was installed, but `libsnapper4` was not.
Then I installed `libsnapper4' which was not on the repository and the version is `0.8.6` but still the same error.

**Comment by aschnell** [comment]
Can you try to reinstall libsnapper from the repository?

**Comment by nemonein** [comment]
Oh!!
It works now!
Reinstalling the libsnapper package(0.8.16-1) solves the problem.
Thank you very much.
