### ISSUE TITLE
snapper fails to build on 32 bit architectures

### ISSUE THREAD

**Issue by fcolista** [openSUSE/snapper#644]
While building snapper on x86_64 works, 32 bit arches are failing with the following error on alpine linux (which is based on musl library):

```
cleanup.cc: In instantiation of 'void Parameters::read(const ProxyConfig&, const char*, Type&) [with Type = long long int]':
cleanup.cc:483:43: required from here
cleanup.cc:72:9: error: request for member 'parse' in 'value', which is of non-class type 'long long int'
 72 | value.parse(pos->second);
 | ~~~~~~^~~~~
```

.: Francesco

**Comment by aschnell** [comment]
On glibc based 32 bit systems compilation works. AFAIS ```time_t``` is ```long long int``` on musl so the special ```read``` function does not match.
