### ISSUE TITLE
Snapper broken on arch after updating to btrfs-progs-5.12-1-x86_64

### ISSUE THREAD

**Issue by bjarnirafn** [openSUSE/snapper#653]
I'm running arch. Just updated btrfs-progs to 5.12-1 and snapper stops working with the error
`snapper: symbol lookup error: /usr/lib/libbtrfs.so.0: undefined symbol: btrfs_device_size`

**Comment by rwtallant13** [comment]
Same exact issues here.
![image](https://user-images.githubusercontent.com/10453230/117923215-32879a00-b2e3-11eb-84f4-a4c4715a50fa.png)
