### ISSUE TITLE
securelibdir determined incorrectly on riscv

### ISSUE THREAD

**Issue by GreatEmerald** [openSUSE/snapper#659]
We have a report that on the riscv architecture, the install script misdetects the library path for pam_snapper.so and puts it into a directory with the ABI name rater than in a lib directory. I'm guessing the `$(libdir)` is wrongly determined here:

https://github.com/openSUSE/snapper/blob/23a6bdfefa49b737557b04237d29e93fc3b4f435/pam/Makefile.am#L11

It gets installed into `/lp64d/security/`, which does not exist.

Downstream bug report: https://bugs.gentoo.org/796179

**Comment by aschnell** [comment]
So is libdir = /usr/lp64d and the correct dir for pam plugins is /lib64?

**Comment by GreatEmerald** [comment]
From what I can tell, libdir = /lp64d, no /usr. I'm not entirely certain what the correct dir is, it's either lib or lib64.

**Comment by aschnell** [comment]
Also see https://github.com/linux-pam/linux-pam/issues/256.

**Comment by aschnell** [comment]
The reference to linux-pam shows that an automatic detection of the correct path is no far provided.

I have added the configure option ```--with-pam-security``` that can be used if the default does not fit.
