### ISSUE TITLE
Snapper config created outside root cannot rollback (`snapper -c home create-config /home`)

### ISSUE THREAD

**Issue by patarapolw** [openSUSE/snapper#664]
`snapper -c home create-config /home` works, but `snapper -c home rollback $n` results in an error.

Also, I am not really sure how to manage snapper outside `/`.

My thought is, these folders should be excluded.

```
- $HOME/.cache
- $HOME/.var
- $HOME/Downloads
- $HOME/.local/share/Steam
- $HOME/.local/share/containers
```

**Comment by aschnell** [comment]
Yes, rollback only works for ```/```. Since rollback works by setting the default subvolume of the btrfs it can only work for one subvolume.

If you want to exclude directories you have to  setup subvolumes. With btrfs snapshots always work on a subvolume.

**Comment by patarapolw** [comment]
My guess is, rolling back `home` can be done by editing `/etc/fstab`, for example.

```sh
➜  ~ sudo btrfs sub list /
...
ID 258 gen 58432 top level 256 path @/home
...
ID 926 gen 58384 top level 258 path @/home/.snapshots
ID 928 gen 58383 top level 926 path @/home/.snapshots/1/snapshot
...
➜  ~ 
```

`/etc/fstab` can be edited.

```sh
# UUID=153398e6-a79c-4a4f-9650-bc435b6a4182	/home     	btrfs     	rw,noatime,compress=zstd:15,ssd,space_cache,subvolid=258,subvol=/@/home,discard=async	0 0
UUID=153398e6-a79c-4a4f-9650-bc435b6a4182	/home     	btrfs     	rw,noatime,compress=zstd:15,ssd,space_cache,subvolid=928,subvol=/@/home/.snapshots/1/snapshot,discard=async	0 0
```

However, I also see that an automated script can also be done.

```sh
# snapper -c home rollback $n

export MNT=/home/.snapshots/$n/snapshot
export SUBVOLID=$(btrfs sub list / | grep "@$MNT" | grep -oP '(?<=ID )[0-9]+')

export MNT=${MNT//\//\\\/}
export SUBVOLID=${SUBVOLID//\//\\\/}

sed -i -E "s/subvolid=\d+,subvol=\/@\/home(,| )/subvolid=$SUBVOLID,subvol=/@$MNT\1/g" /etc/fstab
mount -a
```

**Comment by aschnell** [comment]
You can "rollback" subvolumes like that. But one consequence is that a rollback of ```/``` can cause other rollbacks as well. In any way it is not supported by snapper.
