### ISSUE TITLE
snapper diff n...p /var/lib/docker says file not found. Does snapper support folder rollbacks?

### ISSUE THREAD

**Issue by develroo** [openSUSE/snapper#685]
Hey guys, maybe I am misunderstanding the usage here, but snapper can see all the changes in /var/lib/docker with `snapper --no-dbus diff  2166..2204` but if I do `snapper --no-dbus diff  2166..2204   /var/lib/docker/` I get this. 

```
snapper --no-dbus diff  2166..2204   /var/lib/docker
loading 1618 failed
loading 1619 failed
loading 2993 failed
loading 3015 failed
File '/var/lib/docker' not found.

```

I have to use `--no-dbus` or I get this error.

```
snapper  diff  2166..2204   /var/lib/docker
Failure (org.freedesktop.DBus.Error.NoReply).

```

So how do I undo changes to `/var/lib/docker` and does the `/var/lib/docker/btrfs` subvolume cause issues ? 

```
 snapper --no-dbus diff  2166..2204   /var/lib/docker/*
loading 1618 failed
loading 1619 failed
loading 2993 failed
loading 3015 failed
File '/var/lib/docker/btrfs' not found.

```
Is it possible to undo changes to an entire folder with snapper? And is it possible to be selective and exclude other changes ? I don't really want to have roll back the entire root filesystem but is that the only solution? 

TIA

**Comment by aschnell** [comment]
Only the "root" config (which corresponds to a btrfs subvolumes) can be rolled back. Rollback of individual folders is not possible.

**Comment by develroo** [comment]
ok fair enough
