### ISSUE TITLE
Please not create new snapshots in home or root directory because of bad security

### ISSUE THREAD

**Issue by Zesko** [openSUSE/snapper#690]
`snapper -c home create` creates a new snapshot in the directory `/home/.snapshots/` by default.
`snapper -c root create` creates a new snapshot in the directory `/.snapshots/` by default.

```
├── @/
│ ├── .snapshots/
│ └── ....
├── @home/
│  └── ....
│  └── .snapshots/
              └── 1/
                   └── snapshot/
                          └── .snapshots/
                                     
```

Both are located in the sub-directories of the file system. But what happens when home-directory gets corrupted by any virus (e.g. the known virus `WannaCry` that could completely encrypt all data in home directory including .snapshots) That means all recursions .snapshots will be corrupted too.

The best way is to create @snapshots as new subvolume on the first level like @root and @home, please not in sub-directory.

```
├── @/
│  └── ....
├── @home/
│  └── ....
├── @snapshots/
│  └── home/
│  └── root/

```
@snapshots is safe. Useless virus can not come, when @snapshot is not mounted.

**Comment by aschnell** [comment]
Why should a virus not mount @snapshots?

Use backups to prevent data loss by viruses.
