### ISSUE TITLE
snapper works very slowly on my computer.

### ISSUE THREAD

**Issue by daiaji** [openSUSE/snapper#692]
How can I debug snapper.

**Comment by aschnell** [comment]
The first question is what exactly is slow.

You can also try snapper with the ```--no-dbus``` option to check whether DBus is slow. Also have a look at /var/log/snapper - it includes some time measurements (stopwatch).

**Comment by daiaji** [comment]
https://gist.github.com/daiaji/eaf96ef472fb3b229812e64cff0d632b
`sudo snapper --no-dbus list`
Specifically, it seems that running this command can take a minute or two, I checked the logs, but all the steps seem to take a very long time.
