### ISSUE TITLE
Adding an invalid config entry to SNAPPER_CONFIGS makes any other entry to silently fail to load

### ISSUE THREAD

**Issue by knoopx** [openSUSE/snapper#718]
Recently snapper stopped working and couldn't figure why. 
It did not find any of my configs, which did exist on `/etc/snapper/configs/` (archlinux) and had proper permissions 

Then I realised there was a `config` entry I don't recall adding at the very beginning of `SNAPPER_CONFIGS`:
```
knoopx@desktop /etc> cat /etc/conf.d/snapper 
## Path: System/Snapper

## Type:        string
## Default:     ""
# List of snapper configurations.
SNAPPER_CONFIGS="config root home"
```

After removing it, snapper started working again and found the rest of the configs.

---

```
knoopx@desktop /etc> snapper --version
snapper 0.10.1
flags btrfs,lvm,ext4,xattrs,rollback,btrfs-quota,no-selinux
```

**Comment by aschnell** [comment]
See https://github.com/openSUSE/snapper/issues/715.
