### ISSUE TITLE
Booting from snapshots fails

### ISSUE THREAD

**Issue by sandikata** [openSUSE/snapper#723]
Hello, 

I have troubles with snapper tool, it creates snapshots but if I try to boot some of them the system won't boot, as it's read-only.
Is it there any possible way for snapper to be configured for read-write snapshots (which in theory should boot successfully)?

Regards,
Rosen Aleksandrov

**Comment by aschnell** [comment]
snapper has the option ```--read-write``` for the create command.

In openSUSE the workflow is to boot a read-only snapshot and then call ```snapper rollback``` which also sets the new default subvolume. But if you are not using openSUSE the system might not be setup do support that.

Anyway, if the snapshot you want to use is read-only you could use ``snapper create --read-write --from N``` to get a read-write snapshot and then boot that. With ```btrfs``` is is also possible to change the read-only flag of a snapshot.
