### ISSUE TITLE
Snapper Failure : Creating config failed (sysconfig-file not found).

### ISSUE THREAD

**Issue by SolarAquarion** [openSUSE/snapper#733]
Which is a strange sort of error

But I also get this 

Creating config failed (creating btrfs subvolume .snapshots failed since it already exists)

**Comment by aschnell** [comment]
"sysconfig-file not found" arises when the file /etc/sysconfig/snapper does not exist (the path can be different depending on the distribution). The file is usually packaged with snapper.

And when creating a config the subvolume .snapshots must not exist yet.

**Comment by SolarAquarion** [comment]
@aschnell do i need to delete my /.snapshot folder and btrfs mount?

**Comment by aschnell** [comment]
Yes, unmount /.snapshots and remove or rename it.
