### ISSUE TITLE
Fedora & cronie: Where is the crontab?

### ISSUE THREAD

**Issue by taoeffect** [openSUSE/snapper#744]
Hi, I'm using Fedora with `cronie` installed, and I've following the instructions here: https://wiki.archlinux.org/title/Snapper#Creating_a_new_configuration

```
# snapper -c home create-config /@home
```

However, I can't for the life of me figure out where snapper is storing its cron information.

I tried searching in `/etc/cron*` and `/var/spool/cron/` and don't see anything snapper related.

The docs say that if cronie is installed snapper will automatically use it, but I don't see any new files or crontabs or whatever.

So where does snapper interface with cronie? Or is there a bug with Fedora+cronie integration? (If so, how do I manually tell it to run the timeline snapshots for all configs via a cron job?)

**Comment by aschnell** [comment]
snapper comes with files for cron and systemd timers. Likely Fedora is using the systemd timers. You can check that with e.g. ```systemctl status snapper-cleanup.timer```.

**Comment by aschnell** [comment]
I assume that distributors either package cron or systemd files. You can check that by listing the files of snapper using ```rpm -ql snapper```. Check all snapper rpms.

**Comment by taoeffect** [comment]
Thank you @aschnell. I'll go ahead and close this issue.

I will also note the following:

I shouldn't have used `snapper -c home create-config /@home`, but `snapper -c home create-config /home` instead (pointing it to the mountpoint instead of the snapshot)

And indeed, after fixing that, it seems like the systemd timers are the way to go on Fedora, at least, that's my current best guess. I didn't see any cron related filed from `rpm -ql snapper`.

Thanks again for your help.
