### ISSUE TITLE
Snapper does not clean, when you have nested snapshots

### ISSUE THREAD

**Issue by dsvi** [openSUSE/snapper#748]
If you happened to have a nested snapshot on a filesystem (for example docker likes to create plenty), snapper can't clean it anymore and it stays dirty. I presume because `btrfs subvolume delete` returns "not empty" error, after which snapper just aborts cleanup.

Idealy it should detect und delete the nested ones.
... or at least keep trying to delete others, aftrer one had failed.

**Comment by aschnell** [comment]
The right place to fix this is docker or whatever creates the nested snapshots.
