### ISSUE TITLE
RFE: allow create snaphots every minute

### ISSUE THREAD

**Issue by kloczek** [openSUSE/snapper#778]
It would be good to have as well possibily to create shapshots every minute.

**Comment by aschnell** [comment]
This should be easy by overriding some values from snapper-timeline.timer using systemd drop-in (systemctl edit).

**Comment by kloczek** [comment]
So this ferure is now implemented? 🤔 
Sorry for asking but I don't see anything in last commits ..

**Comment by aschnell** [comment]
No, you can simply modify the systemd timer for your needs using e.g. a drop-in (systemctl edit).

**Comment by kloczek** [comment]
Can you drop zom command how can I do that?
Even if it will be ossible to change rate of timer timer execution still it it will be not possible to have separated queue for minuely made shapshots in volume settings snapshots like `TIMELINE_LIMIT_MINUTELY`. 🤔

**Comment by aschnell** [comment]
Run ```systemctl edit snapper-timeline.timer``` and enter:

[Timer]
OnCalendar=minutely

Using ```TIMELINE_MIN_AGE``` you have some control over the number of snapshots to keep.
