### ISSUE TITLE
provide set-default command

### ISSUE THREAD

**Issue by lnussel** [openSUSE/snapper#803]
transactional-update resp tukit do not use the regular rollback feature of snapper as all snapshots are read-only and directly bootable. Instead they just set the btrfs default subvolume. Since snapper provides no command for that, tukit calls the btrfs tool directly (https://github.com/openSUSE/transactional-update/blob/e92ce8425323bb1b547cab5104cc380cfc523fc7/lib/Snapshot/Snapper.cpp#L144)

I need to hook into the snapper `set-default-snapshot` hook to update the bootloader config though.
Could snapper implement a `set-default-snapshot` command that also calls the hook?

See also https://github.com/openSUSE/transactional-update/issues/85

**Comment by aschnell** [comment]
Should be simple enough. I would likely not pass the "set-default" through DBus but instead implement directly in the client (like it is for rollback). That also means the hook will be called from the client program, not the server.

Usage might be 'snapper modify --default 123'.
