### ISSUE TITLE
show read-only state in list output

### ISSUE THREAD

**Issue by lnussel** [openSUSE/snapper#804]
Looking at https://github.com/openSUSE/transactional-update/blob/master/lib/Snapshot/Snapper.cpp#L134, transactional-update needs to query and set the read-only property of snapshots. How about implementing that in snapper directly?

**Comment by aschnell** [comment]
Should also be simple (like #803). Here also the "set-read-only" would likely not be pass through DBus.

Usage might be 'snapper modify --read-only/--read-write 123'.
