### ISSUE TITLE
Fedora 38 Support

### ISSUE THREAD

**Issue by blueOkiris** [openSUSE/snapper#810]
It appears I cannot update snapper after migrating to Fedora 38 due to gpg issues. Even with `--nogpgcheck`, there is then a signature error.

On the downloads page, I don't see Fedora 38 yet, so I'm assuming it's not yet supported or something?

**Comment by aschnell** [comment]
There is a setup problem with Fedora 38 in the Open Buildservice: https://build.opensuse.org/package/show/filesystems:snapper/snapper shows the error "unresolvable: have choice for (util-linux-core or util-linux) needed by systemd: util-linux util-linux-core"

**Comment by aschnell** [comment]
It's building now.
