### ISSUE TITLE
How do I create a snapshot that never get deleted by the snapper-cleanup?

### ISSUE THREAD

**Issue by tav9122** [openSUSE/snapper#815]
As the title, I have a snapshot that I want to set as "base" the clean one with only important packages

**Comment by ajgringo619** [comment]
Just remove the cleanup algorithm for the snapshot you want to keep:
```
sudo snapper modify --cleanup-algorithm "" snapshot_number
```

**Comment by aschnell** [comment]
Just one comment: The empty-pre-post cleanup algorithm might still remove the snapshot. If that is a problem the empty-pre-post cleanup algorithm can be disabled completely.
