### ISSUE TITLE
Doc: snapper-boot: Invalid user from network user

### ISSUE THREAD

**Issue by lmf-mx** [openSUSE/snapper#823]
Given a config with the following set
```
SYNC_ACL="yes"
ALLOW_USERS="<sssd user>"
```
snapper-boot throws an `Invalid user` and exits.
This is likely caused by sssd not being loaded when snapper-boot runs. It may also be return behavior similar to what was fixed in https://github.com/SSSD/sssd/issues/3481, but I don't believe so.

Switching to `ALLOW_GROUPS` and utilizing a local group, such as **sudo** that contains the sssd(network) user is a simple workaround. I believe the only correct solution is to document this case, behavior, and workaround.

**Comment by aschnell** [comment]
Since I do not know how sssd works I cannot really comment on the problem itself.

But adding "After=sssd.service" in the Unit section in snapper-boot.timer should ensure that sssd is started first.

**Comment by lmf-mx** [comment]
That will certainly delay the load until sssd, but I think the generally preferred outcome would be to snapshot as early as possible.

**Comment by aschnell** [comment]
Likely it is enough to use "After=nss-user-lookup.target" (see man systemd.special). But yes, it will delay creating the snapshot. So either avoid network users as you did or delay the snapshot creation.
