### ISSUE TITLE
Leap 15.5 installer formats root partition with btrfs withut snapshot support.

### ISSUE THREAD

**Issue by JacekRuzyczka** [openSUSE/snapper#827]
I've recently had to reinstall OpenSuSE Leap 15.5 on my home server. The installer suggested a "transcational server" setup, so I 've got a `btrfs` on my root partition, but unfortunately without support for making snapshots! Consequence: I can't update my system or install additional software (no matter whether by using YaST or the Zypper CLI), as `/` is read-only:

```sh
valen:~ # zypper update
[…]
error: can't create transaction lock on /usr/lib/sysimage/rpm/.rpm.lock (Read-only file system)
```

Using `transactional-update` ends with a complaint about the missing snapshot feature:

```sh
valen:~ # transactional-update
Checking for newer version.
transactional-update 4.1.0 started
Options:
ERROR: no snapshots for root file system configured!
transactional-update finished
```

I found a note in the docs that it's possible to retrofit `btrfs` with snapshots, but the corresponding checkbox in YaST (disk partitioner) is disabled, and doing it by hand ends in a failure ('cause the root fs in read-only, I suppose):

```sh
valen:~ # snapper -c root create-config /
Creating config file failed (creating btrfs subvolume .snapshots failed).
```

Neither have I found a way to circumvent the read-only feature of the root fs. What's wrong here?

**Comment by aschnell** [comment]
We will likely need the (YaST) logs from the installation. And please report this at the openSUSE bugzilla since this does not look like a problem of snapper itself.

**Comment by JacekRuzyczka** [comment]
Bugzilla won't let me in with my account :-( And please tell me anyway how I can create snapshots on my system despite the read-only root of. Thank you.

**Comment by aschnell** [comment]
Sorry, I cannot answer these question. This is not a support forum.
