### ISSUE TITLE
Having snapperd create timestamped snapshot directories?

### ISSUE THREAD

**Issue by mrjpaxton** [openSUSE/snapper#828]
Hey guys, I have a question about Snapper. I was wondering if there is a way to change the directory names `snapperd` uses when creating hourly read-only snapshots. For example, in `.snapshots/` directories, confusing ID numbers are created, and I have to look at the stats like mtime to figure out when the snapshots were created. It would be nice if I could format them along the lines of using `strftime`.

So for example, the `.snapshots/` directory looks something like this:

```
./snapshots/1378
./snapshots/2256
./snapshots/2257
./snapshots/2258
```

But I want something like this in (YYYY-MM-DD) format:

```
./snapshots/2022-09-07-1230-0800PST
./snapshots/2023-07-05-0300-0700PDT
./snapshots/2023-07-05-0400-0700PDT
./snapshots/2023-07-05-0500-0700PDT
```

Now I realize that doing this should still keep the directories unique *for the most part*, since it takes account of time zones and DST changes, but there may be errors in uniqueness in the case of leap years and leap days in the Gregorian calendar. So if there is a more preferred timestamp format to make each directory name still have a unique ID, then please let me know. There will also be errors if the user/machine decides to manipulate and change the system clock, I do realize that. We have to account for all possible problems.

Is there any way to do this? If not, then this is a feature request!

**Comment by ajgringo619** [comment]
The data you want can be easily read from the `info.xml` files in each directory, or just use `snapper ls` to get the creation date. Are you trying to create a program to do this?

**Comment by aschnell** [comment]
I do not see the use case as already mentioned ```snapper ls``` provides the date and time.

But to answer the question: Generating directories like that is currently not possible.
