### ISSUE TITLE
snapper support for Ceph RBD and CephFS snapshots

### ISSUE THREAD

**Issue by gnyers** [openSUSE/snapper#85]
What are the plans on supporting the Ceph RBD and CephFS snapshots? 
https://ceph.com/docs/master/rbd/rbd-snapshot/

**Comment by BlackLotus** [comment]
is this still not planned?

**Comment by ls-initiatives** [comment]
CephFS snapshots are a stable feature now (since Ceph 13.2 "mimic").
At first glance it's quite simple to use :
`mkdir <directory>/.snap/<snapshot-name>` to create a snapshot.
`rmdir <directory>/.snap/<snapshot-name>` to delete it.

Would it fit in the snapper logic ?

**Comment by jonesmz** [comment]
I am interested in support for this.

If someone familiar with the code could point me in the right direction, I'm willing to work on a pull request to implement the first pass for this feature.

**Comment by Hoeze** [comment]
Any updates on this?
I'm using Snapper at home and it's great. Having it for CephFS would be awesome!

**Comment by 0xFEEDC0DE64** [comment]
is anyone else using cephfs just to offsite store the backups made by snapper from a (not clustered) machine like a laptop?

I have a temporary btrfs filesystem at home that I incrementally sync my snapper snapshots from my laptop to, and then I do an rsync from the btrfs received snapshot to cephfs, create a snapshot there and delete the parent btrfs snapshot on the btrfs filesystem.

laptop-btrfs with snapper -> incr send -> temporary btrfs to receive -> rsync to cephfs -> create snapshots there -> delete btrfs parent snapshot to save on storage

I dont know if this is a workaround/solution to the refusal of snapper devs to actually support such a great fs as cephfs.
