### ISSUE TITLE
Add --dry-run option for cleanup

### ISSUE THREAD

**Issue by haselwarter** [openSUSE/snapper#851]
It would help with creating cleanup policies to have a --dry-run flag, which does not actually perform the cleanup but only lists which changes would be made.

**Comment by aschnell** [comment]
Unfortunately that look impossible since the cleanup algorithms need (depending on the configuration) disk usage information that is only up-to-date after removing snapshots.

**Comment by haselwarter** [comment]
snapper could still report an conservative over-approximation of snapshots that would be deleted, since freeing up space during cleanup will only cause fewer snapshots to be deleted. In practice this would still be very useful for users not relying on space based policies, and would not be harmful for those who do, since a real run would not delete more than a dry run would predict.
