### ISSUE TITLE
duplicate pre snapshots when updating with nala

### ISSUE THREAD

**Issue by tehbuhtig** [openSUSE/snapper#860]
Hey guys. Thanks for snapper, it's a great tool!

I'm using snapper on latest Debian stable, currently version 12.4. Snapper was installed from the repos, along with nala, which is a nice wrapper for apt. When I update packages using nala, I get pre and post update snapshots as expected, but also a duplicate pre update snapshot. Both pre snapshots seem fine (e.g. I can boot from both and the system looks the same after a quick check). So far I have been dealing with it by just manually deleting the duplicate snapshots every so often. 

There are no such duplicate entries when updating using apt. 

I'm not sure if this is a snapper issue or a nala issue, but figured I would start here first as the problem seems more closely related to snapper than to nala.

Thanks!

**Comment by aschnell** [comment]
To me this looks more like a problem of nala or apt since snapper only makes a snapshot when instructed to do so. Please contact the developers of those tools.

**Comment by tehbuhtig** [comment]
okie dokie. created an issue on the nala gitlab page [here](https://gitlab.com/volian/nala/-/issues/287).

**Comment by aschnell** [comment]
So this was a bug is nala and is fixed now.
