### ISSUE TITLE
Change default cleanup timer interval to 1h, to match default LIMIT_HOURLY

### ISSUE THREAD

**Issue by infinity0** [openSUSE/snapper#885]
It doesn't make much sense to have a default LIMIT_HOURLY of 10 but a cleanup OnUnitActiveSec of 1 day. In fact any value of LIMIT_HOURLY above 1 should have a corresponding cleanup OnUnitActiveSec of 1 hour.

Responding to #568:

> And the behaviour also seems better to me: Suppose the timeline would keep the hourly snapshots of the last 10 hours. Now the system is turned on after two days and as a result all hourly snapshots are removed. That renders the timeline useless.

If the system is turned on after two days and LIMIT_DAILY is 0 or 1 or 2 and all hourly snapshots are removed, this is *precisely what the user wanted*.

If the system is turned on after two days and LIMIT_DAILY is >2 and all hourly snapshots are removed, then some daily snapshots will still remain. Again, this is *precisely what the user wanted*.

If instead you think it's "more useful" to retain the last 10 hourly backups **regardless of age**, then that is not what `snapper-cleanup` currently does *nor how it is advertised*. It could be changed to do that, and in fact I wouldn't mind that at all, but it should be done to all the LIMIT_*s so they behave the same way, not just hourly ones.

In any case, that would be an issue **separate** from the issue here - which is the effective **inconsistency** between LIMIT_HOURLY and the other LIMIT_*s. The current behaviour is *not* intuitive and is not what most users actually want. LIMIT_HOURLY in effect is not a **maximum limit** like the other limits, it is a **minimum limit** with the actual maximum limit being 24, equal to the default cleanup OnUnitActiveSec.

**Comment by infinity0** [comment]
BTW `rsnapshot(1)` implements retention regardless of age; its algorithm could be used instead if you think that behaviour is better. That would cover your example of wanting to retain 10 hourly backups after 2 days of downtime.

To re-iterate however, that's not the behaviour currently advertised by `snapper(1)`.

**Comment by madscientist16** [comment]
I was really confused when I saw several hourly snapshots even though I set LIMIT_HOURLY to 0. I think this would be a good change.
