### ISSUE TITLE
Small doubt/problem with submodules on / and /home

### ISSUE THREAD

**Issue by MrDuartePT** [openSUSE/snapper#890]
I configure snapper to create snapshot for / and /home.
The problem is I have /usr as a subvolume and /home/mrduarte/Onedrive and other and I noticing that my snapshot are not saving snapshoting this folder.

The stange thing is /opt is on another subvolume and the files are being snapshot.

Subvolume List:
```
mrduarte@GentooLegion ~ $ doas btrfs subvolume list /
doas (mrduarte@GentooLegion) password:
ID 256 gen 70006 top level 5 path @
ID 257 gen 70003 top level 5 path @root
ID 258 gen 70010 top level 5 path @usr
ID 259 gen 70026 top level 5 path @var
ID 260 gen 45309 top level 5 path @opt
ID 261 gen 45374 top level 256 path srv
ID 262 gen 45374 top level 259 path @var/lib/portables
ID 263 gen 45374 top level 259 path @var/lib/machines
....
ID 353 gen 69928 top level 5 path @.snapshots
ID 356 gen 69919 top level 353 path @.snapshots/1/snapshot
ID 357 gen 69923 top level 353 path @.snapshots/2/snapshot

mrduarte@GentooLegion ~ $ doas btrfs subvolume list /home
ID 256 gen 71619 top level 5 path @home
ID 257 gen 61376 top level 5 path @games
ID 258 gen 38532 top level 5 path @onedrive
ID 260 gen 50333 top level 5 path @libvirt #/var/lib/libvirt
ID 263 gen 71602 top level 5 path @snapshots-home
ID 264 gen 71600 top level 263 path @snapshots-home/1/snapshot
```

**Comment by MrDuartePT** [comment]
I decided to create a configuration to `/usr` and subvolume to save the snapshot( I don't like the default way of saving inside `@usr/.snapshots`.
I don't think it wasn't affect anything in terms of, for exemple booting the snapshot or restoring.

**Comment by MrDuartePT** [comment]
Also deleted the `/home` config because it seems that snapper not ignore temporary files on home and I can't find a way to ignore some folders or files.

**Comment by aschnell** [comment]
btrfs makes snapshots of subvolumes, so neither directories nor files can be ignored. Creating a subvolume instead of a directory partly solves that but needs special care in /etc/fstab. So you could create a subvolume for e.g. /home/<user>/tmp.

Why usr and opt behave differently is not clear to me.
