### ISSUE TITLE
build fails due to moved libstdc++.la

### ISSUE THREAD

**Issue by ShalokShalom** [openSUSE/snapper#906]
I try to build snapper for a good while, and dont seem to be able to resolve this on my own.

`libtool: warning: '/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libstdc++.la' seems to be moved`

My libstdc++.la sits at `/usr/lib/libstdc++.la` and I dont find any recent issue on this online. 

[Here is my complete build log. 
](https://dpaste.org/q2a1E/raw)

Hope you can help me :/

**Comment by ShalokShalom** [comment]
Thanks! [Those](https://kaosx.us/packages/view.php?name=core/ncurses-6.5-1) are the ncurses files I have installed (listed under "Files listing")

And when I change /client/utils/Makefile.am (there are a lot of Makefile.am, and only this one contains -ltinfo) to -lncurses, it rewrites itself once I build back to -ltinfo.

**Comment by aschnell** [comment]
Makefile.am should not rewrite itself back. Makefile.in and Makefile are generated from Makefile.am but Makefile.am is the source. How are you starting the build?

**Comment by ShalokShalom** [comment]
https://dpaste.org/SyQts

**Comment by aschnell** [comment]
If that is some kind of script that also unpacks the sources then you likely have to create a patch that modifies Makefile.am. Maybe first try to build without such a setup.
