### ISSUE TITLE
Where do I declare custom $SNAPSHOTS path?

### ISSUE THREAD

**Issue by cinnamonmatexfce** [openSUSE/snapper#910]
I'd like to use user-defined destinations paths instead of the default `/.snapshots`.
Eg.: `/0_fedora` or `/0_debian` (accordingly), where `/0_$DISTRONAME` subvolumes are all beneath `ID5`.

Thanks

**Comment by aschnell** [comment]
Specifying the path is so far not possible.

https://github.com/openSUSE/snapper/issues/54
