### ISSUE TITLE
After snapper rollback/restore marks packages as explicitly installed which were autoinstalled previously

### ISSUE THREAD

**Issue by vajdao** [openSUSE/snapper#916]
Yesterday, I accidentally noticed something strange. I don't know if this is how Snapper is supposed to work, but here are my observations and steps to reproduce:

1. I installed `firewall-applet` manually, and zypper marked it with `i+` as explicitly installed. It also pulled `firewall-config` automatically as a dependency (marking it with `i` as auto-installed status) - so far, so good.
2. Then, I did a `sudo zypper rm --clean-deps firewall-applet`, and it perfectly caught `firewall-config` too, as it was installed automatically as a dependency.
3. Next, I did a reboot and told Snapper to use the `post` snapshot from the time when `firewall-applet` was installed. This reverted the removal process to the point where `firewall-applet` was installed instead, so chronologically we are at step 1.
4. In the read-only mode, I did a `zypper se -i firewall-`, and to my surprise, `firewall-config` was also marked with `i+`.
5. I made the `sudo snapper rollback` to see the changes live, and yes, `firewall-config` was still marked with `i+`.
6. When I did `sudo zypper rm --clean-deps firewall-applet`, it no longer recognized `firewall-config` to be auto-removed since it was marked as explicitly installed.
7. This can be also reproduced without rebooting when steps are done from the GUI YaST2 snapshot tool.
8. Since it was late yesterday, I thought I was too tired and maybe misunderstood something. So, I double-checked myself and simulated the steps I made yesterday, just to confirm my theory, and yepp - same results.

No idea why, but snapper removes any affected packages during a snapper procedure within
 `/var/lib/zypp/AutoInstalled` but this step is nowhere logged.

How do we trace back which packages were marked by these rollbacks? As you might guess, there could be plenty of unnecessary packages using extra drive space, now that are explicitly marked and thus never get removed via `sudo zypper dup --remove-orphaned` nor gets listed by `zypper pa --orphaned` or `zypper pa --unneeded` sadly.

**Comment by aschnell** [comment]
/var is a separate subvolume so it will not be changed during rollback. But how this affects zypper I cannot say. Please make a report at bugzilla.opensuse.org.

**Comment by vajdao** [comment]
> /var is a separate subvolume so it will not be changed during rollback. But how this affects zypper I cannot say. Please make a report at bugzilla.opensuse.org.

Done
https://bugzilla.opensuse.org/show_bug.cgi?id=1226517

Also 4 years ago (not mine)
https://bugzilla.opensuse.org/show_bug.cgi?id=1175304
