### ISSUE TITLE
snapper has changed its output (from | to │ )

### ISSUE THREAD

**Issue by dim-geo** [openSUSE/snapper#923]
in version 0.11.0 of snapper I noticed that my tools can no longer parse snapper list because the output has changed.
Instead of using the ascii character `|`  snapper output is using the unicode character `│` thus breaking parsing (regexs).

Is this a bug or a feature?
why did you change the output of snapper?

**Comment by aschnell** [comment]
It is a feature to make the output look better. Use the option --type 0 to get the old look. If you parse the output in programs use the JSON of CSV output format.
