### ISSUE TITLE
Snapper and btrbk?

### ISSUE THREAD

**Issue by 86ul** [openSUSE/snapper#924]
Is it an (good) idea to work with both Snapper, and BTRBK? This way, I can use the Snapper snapshots to compare and restore on disk, while using the BTRBK snapshots to both backup with send/receive to, and rollback from an external disk...

**Comment by aschnell** [comment]
btrbk and btrbk cannot use the snapshots created by snapper. So you will have to use both tools to create snapshots which look expensive. But apart from that it should work.

Also see https://github.com/openSUSE/snapper/issues/368 and https://github.com/digint/btrbk/issues/456.

I leave the question open for others to comment.

**Comment by 86ul** [comment]
Thanks for the response. Those two issues you mentioned made me think if I could use both just side by side. Although there will be more overhead load, I will give these two apps a try together; unless some else advice strongly to do otherwise. 

Just to make clear and as I have mentioned already above, I will use Snapper for Snapper snapshots, and BTRBK for BTRBK snapshots.

In case this issue is still open, when I have tried these two apps together for some time, I will report my findings here too.

**Comment by aschnell** [comment]
You can try the new program snbk, see http://snapper.io/2024/11/11/snbk.html.

**Comment by 86ul** [comment]
> You can try the new program snbk, see http://snapper.io/2024/11/11/snbk.html.

Ah, merci
