### ISSUE TITLE
Configurable snapshot path

### ISSUE THREAD

**Issue by formicant** [openSUSE/snapper#926]
Currently, Snapper creates a subvolume named `.snapshots` inside the snapshotted subvolume and stores snapshots there.

Is it possible to add a parameter to the configuration file (and also to the `create-config` subcommand) allowing to define a custom path for the snapshots directory?

E.g.,
```bash
snapper -c root create-config --snapshots-path /mnt/snapshots /
```
that creates the config file:
```ini
SUBVOLUME=/
SNAPSHOTS_PATH=/mnt/snapshots
. . .
```
and stores all the snapshots inside `/mnt/snapshots`.

If `/mnt/snapshots` and `/` are not subvolumes of the same volume, it could throw an error.

**Comment by cinnamonmatexfce** [comment]
https://github.com/openSUSE/snapper/issues/910#issuecomment-2141747053

**Comment by aschnell** [comment]
See https://github.com/openSUSE/snapper/issues/54.
