### ISSUE TITLE
Support for Simple Quotas

### ISSUE THREAD

**Issue by emanuc** [openSUSE/snapper#943]
Recently, [in kernel 6.7](https://btrfs.readthedocs.io/en/latest/Kernel-by-version.html#jan-2024), a new feature was merged that addresses performance issues when enabling qgroups. If I’m not mistaken, it is used by Snapper, right? For Snapper's use case, is it feasible to use this feature to solve performance problems?

[btrfs: simple quotas](https://lwn.net/Articles/944371/)

Thank you

**Comment by aschnell** [comment]
I have looked at simple quotas some month ago and they do not look usable as a replacement for the current quotas for snapper.
