### ISSUE TITLE
FAQ: snapper limits eg max number of subvols / configs supported

### ISSUE THREAD

**Issue by danboid** [openSUSE/snapper#961]
I have already checked the snapper FAQ ( http://snapper.io/faq.html ) but it doesn't answer my question which is what is the max number of subvolumes that snapper is known to be able to handle?

I run a web server (ubuntu 22.04, 64 GB RAM, 16 xeon cores) that could have up to 1000 users each with their own btrfs subvol. If I configure snapper to allow up about 10 snapshots per subvolume, do you think snapper is going to be able to handle creating snapshots for 800 to ~1000 subvols/users?

What is the largest number off subvolumes / snapper configs per disk or system that snapper has been tested and is known to work with? Are there any snapper or btrfs mount options that I should use if attempting to use snapper with such a large number of subvols?

Thanks

**Comment by aschnell** [comment]
I did a test and created 1000 snapper configs each with 10 snapshots. snapper itself can handle that, e.g. listing all snapshots (snapper list --all) takes 25s and creating a snapshot for all configs (snapper-timeline.service) takes 40s. That itself looks good. The btrfs is on a NVMe, quota is off.

But the filesystem and all snapshots are almost empty. So the next question is whether btrfs can handle this when the filesystem is filled. I cannot answer that and will have to ask btrfs maintainers. Can you give more information about the setup, e.g. NMVe, SSD or HDD and size?

**Comment by aschnell** [comment]
No further input provided.

**Comment by danboid** [comment]
Hi

Sorry, I've only just seen your reply now for some reason.

Its an Azure 1TB SSD.

Thanks
