### ISSUE TITLE
snbk command not found

### ISSUE THREAD

**Issue by rayzorben** [openSUSE/snapper#970]
Looks like maybe it is expecting to find `findmnt` in `/usr/bin` but it is not on this server?

```
❯ snbk list
command "/usr/bin/ssh 192.168.1.50 -i /etc/snapper/certs/id_rsa '/usr/bin/findmnt' '--json' '--target' '/mnt/backup/raytroncachy/home'" not found
command '/usr/bin/ssh 192.168.1.50 -i /etc/snapper/certs/id_rsa '/usr/bin/findmnt' '--json' '--target' '/mnt/backup/raytroncachy/home'' failed: 127
bash: line 1: /usr/bin/findmnt: No such file or directory
'findmnt' failed
Running list failed for 1 of 1 backup config.

/etc/snapper/backup-configs
❯ which ssh
/usr/bin/ssh

/etc/snapper/backup-configs
❯ which findmnt
/usr/bin/findmnt
```

On remote server
```
root@server:~# which findmnt
/bin/findmnt
```

**Comment by rayzorben** [comment]
Looks to be the case

```
❯ /usr/bin/ssh 192.168.1.50 -i /etc/snapper/certs/id_rsa '/usr/bin/findmnt' '--json' '--target' '/mnt/backup/raytroncachy/home'
bash: line 1: /usr/bin/findmnt: No such file or directory

/etc/snapper/backup-configs
❯ /usr/bin/ssh 192.168.1.50 -i /etc/snapper/certs/id_rsa '/bin/findmnt' '--json' '--target' '/mnt/backup/raytroncachy/home'
{
   "filesystems": [
      {
         "target": "/mnt/backup",
         "source": "/dev/sdb1",
         "fstype": "btrfs",
         "options": "rw,noatime,discard=async,space_cache=v2,subvolid=5,subvol=/"
      }
   ]
}
```

**Comment by rayzorben** [comment]
Also btrfs is expected to be in `/usr/sbin/` but it is in `/sbin` on my system (unRAID)

**Comment by aschnell** [comment]
So the binaries are at different locations on the source and target system. Then likely it must be possible to configure the location in the individual config files.

For the time being you could work with symlinks.

**Comment by rayzorben** [comment]
> I have made some paths configurable. For once in configure.ac (that affects both source and target system) and in the backup configs (affect only target). Please give it a try and report if more paths need handling.

Thanks, i'll test this out at some point. I worked around it by soft linking them on the server and it is just those 2 binaries.
