### ISSUE TITLE
snapper ignores snapshots with empty info.xml

### ISSUE THREAD

**Issue by mdhooge** [openSUSE/snapper#98]
Hello.
I'm using snapper (0.2.3) on a debian system with btrfs.

Every time snapper is called (except to get version number), 4 lines are created in /var/log/syslog:
org.opensuse.Snapper[1562]: :1: parser error : Document is empty
org.opensuse.Snapper[1562]: ^
org.opensuse.Snapper[1562]: :1: parser error : Start tag expected, '<' not found
org.opensuse.Snapper[1562]: ^

AFAIK, snapper still works properly, but it fills my logs...

I quickly grep-ped in the code but found nothing. I copied zypp-plugin.conf into /etc/snapper but the problem remains.

Thanks

**Comment by anatol** [comment]
I have the same problem. It would be great if snapper reported *what* file has formatting problem.

**Comment by rumpelsepp** [comment]
> It would be great if snapper reported what file has formatting problem.

That would be nice! Idid a

```
$ find . -name "info.xml" -exec ls -la {} \;
```

and I found the corrupted file very quickly…

**Comment by maridonkers** [comment]
find /.snapshots/ -maxdepth 2 -name "info.xml" - -lls

or even:

file /.snapshots/*/info.xml

**Comment by zoechi** [comment]
I found it with `sudo find . -name "info.xml" -type f -empty` (with BTRFS root being the current directory)

**Comment by equaeghe** [comment]
Would it be possible to have the log message show the file that causes the parse error?

**Comment by aschnell** [comment]
For once snapper does a fsync now after writing info.xml files (see https://github.com/openSUSE/snapper/pull/548). That could help to get rid of empty info.xml files in case of system crashes.

An the other hand the log does include the number of the snapshot that failed to load:
```Snapshot.cc(read):266 - loading 370 failed```
